"""All migration-aligned persistence mappings."""

from .base import Base
from .fact import AIExtraction, Signal, SignalSemanticAudit
from .intelligence import (
    ActivationReviewEvent,
    IntelligenceLocalization,
    Opportunity,
    OpportunityEvidence,
    OpportunityMergeHistory,
    OpportunityRevision,
    OpportunityScore,
    OpportunitySignalLink,
    ReviewTask,
    TrendSnapshot,
    Watchlist,
    WatchlistItem,
)
from .raw import (
    Channel,
    CollectionRun,
    Comment,
    DiscoveryTopic,
    DiscoveryTopicRun,
    SearchQuery,
    UserProfile,
    Video,
    VideoSnapshot,
    YouTubeDiscoveryItem,
)
from .taxonomy import (
    CustomerTaxonomyNode,
    IndustryTaxonomyNode,
    OpportunityTaxonomyMapping,
    SignalTaxonomyMapping,
    TaxonomyAlias,
    TaxonomyLocalization,
)

__all__ = [
    "ActivationReviewEvent",
    "OpportunityRevision",
    "AIExtraction",
    "Base",
    "Channel",
    "CollectionRun",
    "Comment",
    "DiscoveryTopic",
    "DiscoveryTopicRun",
    "IntelligenceLocalization",
    "Opportunity",
    "OpportunityEvidence",
    "OpportunityMergeHistory",
    "OpportunityScore",
    "OpportunitySignalLink",
    "ReviewTask",
    "SearchQuery",
    "Signal",
    "SignalSemanticAudit",
    "TrendSnapshot",
    "UserProfile",
    "Video",
    "VideoSnapshot",
    "Watchlist",
    "WatchlistItem",
    "YouTubeDiscoveryItem",
    "CustomerTaxonomyNode",
    "IndustryTaxonomyNode",
    "OpportunityTaxonomyMapping",
    "SignalTaxonomyMapping",
    "TaxonomyAlias",
    "TaxonomyLocalization",
]
