"use client";

import { FormEvent, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { AlertTriangle, Check, ChevronLeft, ChevronRight, RefreshCw, ShieldCheck } from "lucide-react";
import { ApiClient, ApiError } from "@/lib/api/client";
import { createClient } from "@/lib/auth/client";
import type { CurrentUser, ReviewDecisionName, ReviewListResult, ReviewOpportunityContext, ReviewTask, ReviewType, ReviewWorkflowResult } from "@/lib/api/types";
import { EmptyState, ErrorState } from "@/components/states/states";
import { PageHeader } from "@/components/ui/primitives";

const LIMIT=25;
const REVIEW_TYPES:ReviewType[]=["signal_validation","opportunity_match","opportunity_creation","opportunity_merge","hype_review","quality_review"];
const DECISIONS:Record<ReviewType,ReviewDecisionName[]>={signal_validation:["approve","reject","ignore","defer"],opportunity_match:["approve","merge","create_new","reject","defer"],opportunity_creation:["approve","create_new","reject","defer"],opportunity_merge:["merge","reject","defer"],hype_review:["approve","reject","defer"],quality_review:["approve","reject","ignore","defer"]};
const LABELS:Record<string,string>={signal_validation:"Signal validation",opportunity_match:"Opportunity match",opportunity_creation:"Opportunity creation",opportunity_merge:"Opportunity merge",hype_review:"Hype review",quality_review:"Quality review",approve:"Approve",merge:"Merge",create_new:"Create New",reject:"Reject",ignore:"Ignore",defer:"Defer"};

function date(value:string|null){return value?new Intl.DateTimeFormat("zh-CN",{year:"numeric",month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(value)):"—"}
function value(input:unknown){return input==null||input===""?"—":String(input)}

export function ReviewWorkspace(){
  const router=useRouter();const searchParams=useSearchParams();const serialized=searchParams.toString();const params=useMemo(()=>new URLSearchParams(serialized),[serialized]);
  const status=params.get("status")??"pending";const reviewType=params.get("review_type")??"";const assignedTo=params.get("assigned_to")??"";const offset=Math.max(0,Number(params.get("offset"))||0);const selected=params.get("selected");
  const [user,setUser]=useState<CurrentUser|null>(null);const [queue,setQueue]=useState<ReviewListResult|null>(null);const [task,setTask]=useState<ReviewTask|null>(null);const [loading,setLoading]=useState(true);const [detailLoading,setDetailLoading]=useState(false);const [error,setError]=useState<ApiError|null>(null);const [actionError,setActionError]=useState<ApiError|null>(null);const [submitting,setSubmitting]=useState(false);const [notes,setNotes]=useState("");const [mergeTarget,setMergeTarget]=useState("");const [confirmMerge,setConfirmMerge]=useState(false);const [notice,setNotice]=useState("");const [refresh,setRefresh]=useState(0);

  const navigate=useCallback((updates:Record<string,string|null>,resetOffset=false)=>{const next=new URLSearchParams(serialized);Object.entries(updates).forEach(([key,nextValue])=>nextValue?next.set(key,nextValue):next.delete(key));if(resetOffset)next.delete("offset");const query=next.toString();router.replace(query?`/admin/review?${query}`:"/admin/review")},[router,serialized]);
  const getApi=useCallback(async()=>{const {data:{session}}=await createClient().auth.getSession();if(!session){router.replace("/login");return null}return new ApiClient(async()=>session.access_token)},[router]);
  const filters=useMemo(()=>({status:status||undefined,review_type:reviewType||undefined,assigned_to:assignedTo||undefined,offset,limit:LIMIT}),[assignedTo,offset,reviewType,status]);

  useEffect(()=>{let active=true;async function load(){setLoading(true);setError(null);try{const api=await getApi();if(!api)return;const [current,nextQueue]=await Promise.all([api.getCurrentUser(),api.listReviews(filters)]);if(!active)return;if(current.role!=="admin"){setError(new ApiError(403,"你没有访问审核工作台的权限"));return}setUser(current);setQueue(nextQueue)}catch(reason){if(reason instanceof ApiError&&reason.status===401){router.replace("/login");return}if(active)setError(reason instanceof ApiError?reason:new ApiError(0,"无法加载审核队列"))}finally{if(active)setLoading(false)}}void load();return()=>{active=false}},[filters,getApi,refresh,router]);
  useEffect(()=>{let active=true;if(!selected)return;const selectedId=selected;async function loadDetail(){setDetailLoading(true);setActionError(null);try{const api=await getApi();if(!api)return;const next=await api.getReview(selectedId);if(active){setTask(next);setNotes(next.decision_notes??"");setMergeTarget(defaultMergeTarget(next))}}catch(reason){if(active)setActionError(reason instanceof ApiError?reason:new ApiError(0,"无法加载审核详情"))}finally{if(active)setDetailLoading(false)}}void loadDetail();return()=>{active=false}},[getApi,refresh,selected]);

  const submitFilters=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);navigate({status:String(form.get("status")||""),review_type:String(form.get("review_type")||""),assigned_to:String(form.get("assigned_to")||""),selected:null},true)};
  const claim=async()=>{if(!task||submitting)return;setSubmitting(true);setActionError(null);try{const api=await getApi();if(!api)return;await api.claimReview(task.id);setNotice("Review claimed");setRefresh(count=>count+1)}catch(reason){setActionError(normalizeActionError(reason))}finally{setSubmitting(false)}};
  const decide=async(decision:ReviewDecisionName)=>{if(!task||submitting)return;if(decision==="merge"&&!confirmMerge){setConfirmMerge(true);return}setSubmitting(true);setActionError(null);try{const api=await getApi();if(!api)return;const result=await api.decideReview(task.id,{decision,decision_notes:notes.trim()||null,merge_target_opportunity_id:decision==="merge"?mergeTarget:null});setNotice(successMessage(result));setConfirmMerge(false);const nextQueue=await api.listReviews(filters);setQueue(nextQueue);const next=nextQueue.items.find(item=>item.id!==task.id);navigate({selected:next?.id??null})}catch(reason){setActionError(normalizeActionError(reason))}finally{setSubmitting(false)}};

  return <div className="space-y-5"><PageHeader title="Admin Review" description="Inspect, claim and resolve AI-generated intelligence review tasks." actions={<span className="inline-flex items-center gap-1 text-xs text-slate-500"><ShieldCheck size={15}/>Admin only</span>}/>{notice&&<div role="status" className="flex items-center gap-2 rounded-lg border border-emerald-300 bg-emerald-50 px-4 py-3 text-sm text-emerald-900"><Check size={16}/>{notice}</div>}
    <form key={`${status}-${reviewType}-${assignedTo}`} onSubmit={submitFilters} className="grid gap-3 rounded-lg border bg-white p-3 sm:grid-cols-4 dark:bg-slate-950"><FilterSelect name="status" label="Status" value={status} options={["pending","in_review","resolved","ignored"]}/><FilterSelect name="review_type" label="Review type" value={reviewType} options={REVIEW_TYPES}/><label><span className="mb-1 block text-xs text-slate-500">Assigned reviewer ID</span><input name="assigned_to" defaultValue={assignedTo} className="h-10 w-full rounded-md border bg-transparent px-3 text-sm" placeholder="UUID"/></label><button className="mt-auto h-10 rounded-md bg-slate-950 px-4 text-sm text-white dark:bg-white dark:text-slate-950">应用筛选</button></form>
    {error?<ErrorState message={error.message} requestId={error.requestId??undefined} onRetry={()=>setRefresh(count=>count+1)}/>:<div className="grid min-h-[38rem] gap-4 lg:grid-cols-[22rem_minmax(0,1fr)]"><section aria-labelledby="review-queue" className="overflow-hidden rounded-xl border bg-white dark:bg-slate-950"><div className="flex items-center justify-between border-b px-4 py-3"><h2 id="review-queue" className="font-semibold">Review Queue</h2><button type="button" aria-label="刷新队列" onClick={()=>setRefresh(count=>count+1)}><RefreshCw size={15}/></button></div>{loading?<QueueSkeleton/>:queue?.items.length?<ul className="divide-y">{queue.items.map(item=><QueueItem key={item.id} item={item} selected={selected===item.id} onSelect={()=>navigate({selected:item.id})}/>)}</ul>:<EmptyState title={status==="pending"&&!reviewType&&!assignedTo?"Review queue is clear.":"No review tasks match the current filters."} description="调整筛选或稍后刷新。"/>}<div className="flex justify-between border-t p-3"><button type="button" disabled={offset===0} onClick={()=>navigate({offset:String(Math.max(0,offset-LIMIT))})} className="flex items-center gap-1 text-sm disabled:opacity-40"><ChevronLeft size={14}/>上一页</button><button type="button" disabled={!queue||queue.items.length<LIMIT} onClick={()=>navigate({offset:String(offset+LIMIT)})} className="flex items-center gap-1 text-sm disabled:opacity-40">下一页<ChevronRight size={14}/></button></div></section>
      <section aria-labelledby="review-detail" className="rounded-xl border bg-white p-5 dark:bg-slate-950"><h2 id="review-detail" className="sr-only">Review Detail</h2>{!selected?<EmptyState title="Select a review task" description="从队列中选择任务以查看审核上下文。"/>:detailLoading?<DetailSkeleton/>:actionError?<ActionError error={actionError} onRefresh={()=>setRefresh(count=>count+1)}/>:task?<ReviewDetail task={task} currentUserId={user?.user_profile_id??null} notes={notes} setNotes={setNotes} mergeTarget={mergeTarget} setMergeTarget={setMergeTarget} submitting={submitting} onClaim={claim} onDecision={decide}/>:null}</section></div>}
    {confirmMerge&&task&&<MergeDialog task={task} targetId={mergeTarget} submitting={submitting} onCancel={()=>setConfirmMerge(false)} onConfirm={()=>void decide("merge")}/>}</div>
}

function FilterSelect({name,label,value:current,options}:{name:string;label:string;value:string;options:readonly string[]}){return <label><span className="mb-1 block text-xs text-slate-500">{label}</span><select name={name} defaultValue={current} className="h-10 w-full rounded-md border bg-transparent px-3 text-sm"><option value="">All</option>{options.map(option=><option key={option} value={option}>{LABELS[option]??option}</option>)}</select></label>}
function QueueSkeleton(){return <div aria-label="正在加载审核队列" className="space-y-px">{[1,2,3,4,5].map(item=><div key={item} className="h-24 animate-pulse bg-slate-100 dark:bg-slate-900"/>)}</div>}
function DetailSkeleton(){return <div aria-label="正在加载审核详情" className="space-y-4">{["h-16","h-32","h-48","h-24"].map((style,index)=><div key={index} className={`${style} animate-pulse rounded bg-slate-100 dark:bg-slate-900`}/>)}</div>}
function QueueItem({item,selected,onSelect}:{item:ReviewTask;selected:boolean;onSelect:()=>void}){return <li><button type="button" onClick={onSelect} className={`w-full p-4 text-left ${selected?"bg-slate-100 dark:bg-slate-900":"hover:bg-slate-50 dark:hover:bg-slate-900/60"}`}><div className="flex items-center justify-between gap-2"><span className="text-sm font-semibold">{LABELS[item.review_type]}</span><span className="rounded border px-2 py-0.5 text-[11px]">{item.status}</span></div><p className="mt-2 text-xs text-slate-500">{item.target_type} · priority {item.priority}</p><p className="mt-1 truncate text-xs text-slate-400">{item.assigned_to?`Assigned ${item.assigned_to}`:"Unassigned"} · {date(item.created_at)}</p></button></li>}
function ActionError({error,onRefresh}:{error:ApiError;onRefresh:()=>void}){const title=error.status===409?"This review changed while you were working on it. Refresh to see the latest state.":error.status===404?"Review task not found or unavailable.":error.message;return <ErrorState message={title} requestId={error.requestId??undefined} onRetry={onRefresh}/>}

function ReviewDetail({task,currentUserId,notes,setNotes,mergeTarget,setMergeTarget,submitting,onClaim,onDecision}:{task:ReviewTask;currentUserId:string|null;notes:string;setNotes:(value:string)=>void;mergeTarget:string;setMergeTarget:(value:string)=>void;submitting:boolean;onClaim:()=>void;onDecision:(decision:ReviewDecisionName)=>void}){
  const assignedElsewhere=task.assigned_to!==null&&task.assigned_to!==currentUserId;const resolved=task.status==="resolved"||task.status==="ignored";const canDecide=task.status==="in_review"&&!assignedElsewhere&&!resolved;
  return <div className="space-y-6"><header className="border-b pb-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs uppercase tracking-wide text-slate-500">{task.target_type}</p><h3 className="mt-1 text-xl font-semibold">{LABELS[task.review_type]}</h3></div><span className="rounded border px-2 py-1 text-xs">{task.status}</span></div><dl className="mt-4 grid grid-cols-2 gap-3 text-xs sm:grid-cols-4"><Meta label="Priority" value={task.priority}/><Meta label="Assigned" value={task.assigned_to??"Unassigned"}/><Meta label="Created" value={date(task.created_at)}/><Meta label="Decision" value={task.decision??"—"}/></dl>{task.decision_notes&&<p className="mt-3 rounded bg-slate-50 p-3 text-sm dark:bg-slate-900">Decision notes: {task.decision_notes}</p>}</header>
    <Context task={task} mergeTarget={mergeTarget} setMergeTarget={setMergeTarget}/>
    {!resolved&&<div className="space-y-3 border-t pt-5"><label><span className="mb-1 block text-sm font-medium">Decision notes</span><textarea value={notes} onChange={event=>setNotes(event.target.value)} maxLength={2000} rows={3} className="w-full rounded-md border bg-transparent p-3 text-sm" placeholder="可选：记录人工判断依据"/></label>{task.status==="pending"?<button type="button" disabled={submitting} onClick={onClaim} className="rounded-md bg-slate-950 px-4 py-2 text-sm font-medium text-white disabled:opacity-50 dark:bg-white dark:text-slate-950">{submitting?"提交中…":"Claim Review"}</button>:<div className="flex flex-wrap gap-2">{DECISIONS[task.review_type].map(decision=><button key={decision} type="button" disabled={!canDecide||submitting||(decision==="merge"&&!mergeTarget)} onClick={()=>onDecision(decision)} className={`rounded-md border px-4 py-2 text-sm disabled:opacity-40 ${decision==="merge"||decision==="reject"?"border-amber-400":""}`}>{submitting?"提交中…":LABELS[decision]}</button>)}</div>}{assignedElsewhere&&<p role="note" className="text-sm text-amber-700">Assigned to another administrator. Decision controls are disabled.</p>}</div>}
  </div>
}
function Meta({label,value:content}:{label:string;value:unknown}){return <div><dt className="text-slate-500">{label}</dt><dd className="mt-1 break-all font-medium">{value(content)}</dd></div>}
function Context({task,mergeTarget,setMergeTarget}:{task:ReviewTask;mergeTarget:string;setMergeTarget:(value:string)=>void}){const context=task.context??{};return <div className="space-y-5">{context.signal&&<SignalContext signal={context.signal}/>} {(context.reason||context.model_action)&&<section><h4 className="text-sm font-semibold uppercase tracking-wide text-slate-500">AI proposal</h4><dl className="mt-2 grid gap-2 rounded-lg border p-4 sm:grid-cols-2"><Meta label="Proposed action" value={context.model_action}/><Meta label="Reason" value={context.reason}/></dl></section>}{context.candidates?.length?<section><h4 className="text-sm font-semibold uppercase tracking-wide text-slate-500">Candidate opportunities</h4><div className="mt-2 grid gap-3 xl:grid-cols-2">{context.candidates.map(candidate=><OpportunityCard key={candidate.id} opportunity={candidate}/>)}</div>{DECISIONS[task.review_type].includes("merge")&&<label className="mt-3 block"><span className="mb-1 block text-sm font-medium">Canonical merge target</span><select aria-label="Canonical merge target" value={mergeTarget} onChange={event=>setMergeTarget(event.target.value)} className="h-10 w-full rounded-md border bg-transparent px-3 text-sm"><option value="">Select bounded candidate</option>{context.candidates.filter(candidate=>candidate.id!==(context.source_opportunity?.id??task.target_id)).map(candidate=><option key={candidate.id} value={candidate.id}>{candidate.name}</option>)}</select></label>}</section>:null}{task.review_type==="opportunity_merge"&&<section><div className="grid gap-3 xl:grid-cols-2"><div><h4 className="mb-2 text-xs font-semibold uppercase text-slate-500">Source opportunity</h4>{context.source_opportunity?<OpportunityCard opportunity={context.source_opportunity}/>:<InvalidContext/>}</div><div><h4 className="mb-2 text-xs font-semibold uppercase text-slate-500">Canonical target</h4>{context.canonical_opportunity?<OpportunityCard opportunity={context.canonical_opportunity}/>:<InvalidContext/>}</div></div><div className="mt-3 rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm text-amber-950 dark:bg-amber-950 dark:text-amber-100"><AlertTriangle size={16} className="mr-2 inline"/>Merge preserves historical score/trend records on the original opportunity. The source is not deleted.</div></section>}{!context.signal&&!context.candidates?.length&&!context.source_opportunity&&<InvalidContext/>}</div>}
function SignalContext({signal}:{signal:NonNullable<ReviewTask["context"]>["signal"]}){if(!signal)return null;const fields=[["Signal Type",signal.signal_type],["Statement",signal.statement],["Evidence Text",signal.evidence_text],["Claim Status",signal.claim_status],["Confidence",signal.confidence],["Evidence Strength",signal.evidence_strength],["Industry",signal.industry],["Customer",signal.customer_type],["Problem",signal.problem],["Solution",signal.solution],["Observed At",date(signal.observed_at)],["Source",signal.source_type]].filter((entry):entry is [string,string]=>entry[1]!=null&&entry[1]!=="");return <section><h4 className="text-sm font-semibold uppercase tracking-wide text-slate-500">Source signal</h4><dl className="mt-2 grid gap-px overflow-hidden rounded-lg border bg-slate-200 sm:grid-cols-2 dark:bg-slate-800">{fields.map(([label,content])=><div key={label} className="bg-white p-3 dark:bg-slate-950"><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-1 text-sm leading-6">{content}</dd></div>)}</dl></section>}
function OpportunityCard({opportunity}:{opportunity:ReviewOpportunityContext}){return <dl className="rounded-lg border p-4"><Meta label="Name" value={opportunity.name}/>{[["Thesis",opportunity.one_line_thesis],["Industry",opportunity.industry],["Customer",opportunity.customer_type],["Problem",opportunity.problem],["Solution",opportunity.solution],["Market stage",opportunity.market_stage],["First detected",date(opportunity.first_detected_at)],["Last activity",date(opportunity.last_activity_at)]].filter((entry):entry is [string,string]=>entry[1]!=null).map(([label,content])=><div key={label} className="mt-2"><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-0.5 text-sm">{content}</dd></div>)}</dl>}
function InvalidContext(){return <p className="rounded-lg border border-dashed p-4 text-sm text-slate-500">No safe presentation context is available for this task.</p>}
function defaultMergeTarget(task:ReviewTask){return task.context?.canonical_opportunity?.id??task.context?.proposed_opportunity_id??""}
function normalizeActionError(reason:unknown){return reason instanceof ApiError?reason:new ApiError(0,"审核操作失败")}
function successMessage(result:ReviewWorkflowResult){if(result.decision==="defer")return "Review deferred";if(result.decision==="merge")return "Opportunity merged";if(result.decision==="create_new")return "Opportunity created";if(result.decision==="approve")return result.review_type==="signal_validation"?"Signal approved":"Review approved";if(result.decision==="reject")return "Review rejected";if(result.decision==="ignore")return "Review ignored";return "Review updated"}

function MergeDialog({task,targetId,submitting,onCancel,onConfirm}:{task:ReviewTask;targetId:string;submitting:boolean;onCancel:()=>void;onConfirm:()=>void}){const cancelRef=useRef<HTMLButtonElement>(null);useEffect(()=>{cancelRef.current?.focus()},[]);const source=task.context?.source_opportunity?.name??"source opportunity";const target=task.context?.canonical_opportunity?.name??task.context?.candidates?.find(item=>item.id===targetId)?.name??"canonical opportunity";return <div role="dialog" aria-modal="true" aria-labelledby="merge-title" onKeyDown={event=>{if(event.key==="Escape")onCancel()}} className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><div className="max-w-lg rounded-xl bg-white p-6 shadow-xl dark:bg-slate-950"><h2 id="merge-title" className="text-lg font-semibold">Merge “{source}” into “{target}”?</h2><ul className="mt-4 list-disc space-y-2 pl-5 text-sm text-slate-600 dark:text-slate-300"><li>Source will remain in history.</li><li>Links, evidence, and watchlists may move.</li><li>Historical score and trend rows remain on the original record.</li><li>This action cannot be casually undone in v0.1.</li></ul><div className="mt-6 flex justify-end gap-2"><button ref={cancelRef} type="button" onClick={onCancel} className="rounded-md border px-4 py-2 text-sm">取消</button><button type="button" disabled={submitting} onClick={onConfirm} className="rounded-md bg-amber-700 px-4 py-2 text-sm text-white disabled:opacity-50">确认合并</button></div></div></div>}
