"use client";
import Link from "next/link";
import {BarChart3,BriefcaseBusiness,Eye,Radio,Settings,Star} from "lucide-react";
import type {CurrentUser} from "@/lib/api/types";
import {LogoutButton} from "@/components/navigation/logout-button";
import {useI18n} from "@/lib/i18n/context";
const links=[["/radar","nav.radar",BarChart3],["/opportunities","nav.opportunities",BriefcaseBusiness],["/signals","nav.signals",Radio],["/watchlist","nav.watchlist",Star]] as const;
const navClass="flex items-center gap-3 rounded-md px-3 py-2 text-sm hover:bg-slate-100 dark:hover:bg-slate-900";
export function AppShell({user,children}:{user:CurrentUser;children:React.ReactNode}){const {locale,setLocale,t}=useI18n();return <div className="min-h-screen bg-slate-50 text-slate-950 dark:bg-slate-950 dark:text-slate-100"><aside className="fixed inset-y-0 hidden w-60 border-r bg-white p-5 md:block dark:bg-slate-950"><Link href="/radar" className="font-semibold tracking-tight">AI Business Radar</Link><p className="mt-1 text-xs text-slate-500">{t("shell.subtitle")}</p><nav aria-label="main navigation" className="mt-8 space-y-1">{links.map(([href,key,Icon])=><Link key={href} href={href} className={navClass}><Icon size={16}/>{t(key)}</Link>)}{user.role==="admin"&&<div className="mt-5 border-t pt-4"><p className="mb-2 px-3 text-[11px] font-semibold uppercase tracking-wider text-slate-400">{t("shell.reviewWorkspace")}</p><Link href="/admin/review" className={navClass}><Eye size={16}/>{t("nav.review")}</Link><p className="mb-2 mt-4 px-3 text-[11px] font-semibold uppercase tracking-wider text-slate-400">{t("shell.operations")}</p><Link href="/admin/discovery" className={navClass}><Settings size={16}/>{t("nav.discovery")}</Link></div>}</nav></aside><div className="md:pl-60"><header className="flex min-h-16 items-center justify-between gap-3 border-b bg-white px-5 py-2 dark:bg-slate-950"><span className="text-sm text-slate-500">{t("shell.workspace")}</span><div className="flex items-center gap-3 text-sm"><label className="flex items-center gap-2 text-xs text-slate-500"><span className="hidden lg:inline">{t("shell.language")}</span><select aria-label={t("shell.language")} value={locale} onChange={event=>setLocale(event.target.value as "zh-CN"|"en-US")} className="rounded-md border bg-transparent px-2 py-1 text-sm text-slate-900 dark:text-slate-100"><option value="zh-CN">中文</option><option value="en-US">English</option></select></label><span className="hidden sm:inline">{user.email??t("shell.signedIn")}</span>{user.role==="admin"&&<span className="rounded-full bg-slate-900 px-2 py-0.5 text-[11px] font-semibold text-white dark:bg-white dark:text-slate-900">{t("shell.admin")}</span>}<LogoutButton/></div></header><main className="mx-auto max-w-7xl space-y-6 p-5 md:p-8">{children}</main></div></div>}
