"use client";

import Link from "next/link";
import {useRouter,useSearchParams} from "next/navigation";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {ChevronLeft,ChevronRight,Search,X} from "lucide-react";
import {ApiClient,ApiError} from "@/lib/api/client";
import {createClient} from "@/lib/auth/client";
import type {MarketStage,OpportunityLibraryResponse,Query,RadarOpportunity} from "@/lib/api/types";
import {useI18n} from "@/lib/i18n/context";
import {EmptyState,ErrorState} from "@/components/states/states";
import {DataTableShell,PageHeader,ScoreBadge,SkeletonTable,StageBadge} from "@/components/ui/primitives";
import {WatchlistButton} from "@/components/watchlist/watchlist-button";

const STAGES:MarketStage[]=["unknown","emerging","accelerating","validated","crowded","mature","declining"];
const FILTERS=["q","industry_code","customer_code","market_stage","min_score","max_score","min_confidence","max_hype_risk","watchlisted"] as const;
const SORTS=[["last_activity_desc","最近活动"],["first_detected_desc","最新发现"],["score_desc","机会评分"],["confidence_desc","置信度"],["momentum_desc","7日动量"],["name_asc","名称 A–Z"]] as const;
const n=(value:string|null)=>value===null?null:Number(value);
const metric=(value:string|null)=>value===null?"—":Number(value).toFixed(Number.isInteger(Number(value))?0:1);
const date=(value:string,locale:string)=>new Intl.DateTimeFormat(locale,{year:"numeric",month:"short",day:"numeric"}).format(new Date(value));

export function OpportunityLibrary(){
  const {locale}=useI18n(); const router=useRouter(); const search=useSearchParams(); const serialized=search.toString();
  const params=useMemo(()=>new URLSearchParams(serialized),[serialized]);
  const page=Math.max(1,Number(params.get("page"))||1); const size=[20,50,100].includes(Number(params.get("page_size")))?Number(params.get("page_size")):20;
  const sort=SORTS.some(([value])=>value===params.get("sort"))?params.get("sort")!:"last_activity_desc";
  const [data,setData]=useState<OpportunityLibraryResponse|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState<ApiError|null>(null); const [retry,setRetry]=useState(0);
  const replace=(updates:Record<string,string|null>,reset=true)=>{const next=new URLSearchParams(serialized);Object.entries(updates).forEach(([key,value])=>value?next.set(key,value):next.delete(key));if(reset)next.delete("page");router.replace(next.toString()?`/opportunities?${next}`:"/opportunities")};
  useEffect(()=>{let active=true;(async()=>{setLoading(true);setError(null);try{const {data:{session}}=await createClient().auth.getSession();if(!session){router.replace("/login");return}const query:Query={page,page_size:size,sort,locale};FILTERS.forEach(key=>{const value=params.get(key);if(value!==null&&value!=="")query[key]=value});const result=await new ApiClient(async()=>session.access_token).listOpportunities(query);if(active)setData(result)}catch(reason){if(reason instanceof ApiError&&reason.status===401){router.replace("/login");return}if(active)setError(reason instanceof ApiError?reason:new ApiError(0,"无法加载机会库"))}finally{if(active)setLoading(false)}})();return()=>{active=false}},[locale,page,params,retry,router,size,sort]);
  const hasFilters=FILTERS.some(key=>params.has(key));
  const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);const updates:Record<string,string|null>={};FILTERS.forEach(key=>updates[key]=String(form.get(key)??"").trim()||null);replace(updates)};
  const clear=()=>{const next=new URLSearchParams(serialized);FILTERS.forEach(key=>next.delete(key));next.delete("page");router.replace(next.toString()?`/opportunities?${next}`:"/opportunities")};
  return <div className="space-y-5"><PageHeader title={locale==="zh-CN"?"机会库":"Opportunity Library"} description={locale==="zh-CN"?"搜索、筛选和持续跟踪已发布的商业机会。":"Search, filter, and track published business opportunities."}/>
    <form key={serialized} aria-label="机会库筛选" onSubmit={submit} className="rounded-xl border bg-white p-3 dark:bg-slate-950"><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">
      <Field name="q" label="搜索 Search" value={params.get("q")} icon/><Field name="industry_code" label="行业代码 Industry" value={params.get("industry_code")}/><Field name="customer_code" label="客户代码 Customer" value={params.get("customer_code")}/>
      <label><span className="mb-1 block text-xs text-slate-500">市场阶段 Stage</span><select name="market_stage" defaultValue={params.get("market_stage")??""} className="h-10 w-full rounded-md border bg-transparent px-3 text-sm"><option value="">全部 All</option>{STAGES.map(stage=><option key={stage}>{stage}</option>)}</select></label>
      <Field name="min_score" label="最低评分 Min score" value={params.get("min_score")} numeric/><Field name="max_score" label="最高评分 Max score" value={params.get("max_score")} numeric/><Field name="min_confidence" label="最低置信度 Min confidence" value={params.get("min_confidence")} numeric/><Field name="max_hype_risk" label="最高炒作风险 Max hype" value={params.get("max_hype_risk")} numeric/>
      <label className="flex items-end gap-2 pb-2 text-sm"><input type="checkbox" name="watchlisted" value="true" defaultChecked={params.get("watchlisted")==="true"}/>仅看关注 Watchlisted</label><div className="flex items-end gap-2 lg:col-span-3"><button className="h-10 rounded-md bg-slate-950 px-4 text-sm text-white dark:bg-white dark:text-slate-950">应用 Apply</button>{hasFilters&&<button type="button" onClick={clear} className="flex h-10 items-center gap-1 rounded-md border px-3 text-sm"><X size={14}/>清除 Clear</button>}</div>
    </div></form>
    <div className="flex items-center justify-between"><p className="text-sm text-slate-500">{data?`${data.total} 个机会 / opportunities`:"—"}</p><div className="flex gap-2"><select aria-label="排序方式" value={sort} onChange={event=>replace({sort:event.target.value})} className="h-9 rounded-md border bg-transparent px-2 text-sm">{SORTS.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><select aria-label="每页数量" value={size} onChange={event=>replace({page_size:event.target.value})} className="h-9 rounded-md border bg-transparent px-2 text-sm">{[20,50,100].map(value=><option key={value} value={value}>{value}/页</option>)}</select></div></div>
    {loading?<DataTableShell><SkeletonTable/></DataTableShell>:error?<ErrorState message={error.message} requestId={error.requestId??undefined} onRetry={()=>setRetry(value=>value+1)}/>:data?.items.length?<Results items={data.items} locale={locale}/>:<EmptyState title={hasFilters?"没有符合筛选条件的机会":"机会库尚未发布任何机会"} description={hasFilters?"请调整或清除筛选条件。":"通过人工审核并激活的机会会显示在这里。"} action={hasFilters?<button onClick={clear} className="mt-4 rounded-md border px-4 py-2 text-sm">清除筛选</button>:undefined}/>} 
    {!loading&&!error&&data&&data.total_pages>0&&<nav aria-label="分页" className="flex items-center justify-between border-t pt-4"><span className="text-sm text-slate-500">第 {data.page} / {data.total_pages} 页</span><div className="flex gap-2"><button disabled={page<=1} onClick={()=>replace({page:String(page-1)},false)} className="flex items-center rounded-md border px-3 py-2 text-sm disabled:opacity-40"><ChevronLeft size={15}/>上一页</button><button disabled={page>=data.total_pages} onClick={()=>replace({page:String(page+1)},false)} className="flex items-center rounded-md border px-3 py-2 text-sm disabled:opacity-40">下一页<ChevronRight size={15}/></button></div></nav>}
  </div>;
}

function Field({name,label,value,numeric=false,icon=false}:{name:string;label:string;value:string|null;numeric?:boolean;icon?:boolean}){return <label><span className="mb-1 block text-xs text-slate-500">{label}</span><span className="flex items-center rounded-md border px-3">{icon&&<Search size={14}/>}<input name={name} type={numeric?"number":"text"} min={numeric?0:undefined} max={numeric?100:undefined} defaultValue={value??""} className="h-10 min-w-0 flex-1 bg-transparent px-2 text-sm outline-none"/></span></label>}
function Results({items,locale}:{items:RadarOpportunity[];locale:string}){return <DataTableShell><table className="hidden w-full text-left text-sm lg:table"><thead className="border-b bg-slate-50 text-xs text-slate-500 dark:bg-slate-900"><tr>{["Opportunity","Taxonomy","Stage","Score","Confidence","Hype","7d Momentum","Evidence","Dates","Watch"].map(x=><th key={x} className="px-3 py-3">{x}</th>)}</tr></thead><tbody className="divide-y">{items.map(item=><tr key={item.id} className="align-top"><td className="max-w-sm px-3 py-4"><Link href={`/opportunities/${item.slug||item.id}`} className="font-semibold hover:underline">{item.name}</Link><p className="mt-1 line-clamp-2 text-xs text-slate-500">{item.one_line_thesis}</p></td><td className="px-3 py-4 text-xs">{item.industry_taxonomy?.label??item.industry??"—"}<br/>{item.customer_taxonomy?.label??item.customer_type??"—"}</td><td className="px-3 py-4"><StageBadge stage={item.market_stage}/></td><td className="px-3 py-4"><ScoreBadge label="" value={n(item.opportunity_score)}/></td>{[item.confidence_score,item.hype_risk_score,item.trend?.momentum_score??null].map((v,i)=><td key={i} className="px-3 py-4 tabular-nums">{metric(v)}</td>)}<td className="px-3 py-4 text-xs">{item.evidence_summary.active_signal_count} signals<br/>{item.evidence_summary.distinct_video_count} videos · {item.evidence_summary.distinct_channel_count} channels</td><td className="px-3 py-4 text-xs text-slate-500">{date(item.first_detected_at,locale)}<br/>{date(item.last_activity_at,locale)}</td><td className="px-3 py-4"><WatchlistButton opportunityId={item.id} initialWatchlisted={item.watchlisted}/></td></tr>)}</tbody></table><div className="divide-y lg:hidden">{items.map(item=><article key={item.id} className="p-4"><div className="flex justify-between"><Link href={`/opportunities/${item.slug||item.id}`} className="font-semibold">{item.name}</Link><WatchlistButton opportunityId={item.id} initialWatchlisted={item.watchlisted}/></div><p className="mt-2 text-sm text-slate-500">{item.one_line_thesis}</p><div className="mt-3 flex gap-3"><StageBadge stage={item.market_stage}/><span>Score {metric(item.opportunity_score)}</span><span>7d {metric(item.trend?.momentum_score??null)}</span></div></article>)}</div></DataTableShell>}
