import { cleanup, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { ReviewWorkspace } from "@/components/reviews/review-workspace";
import type { CurrentUser, ReviewTask, ReviewWorkflowResult } from "@/lib/api/types";

const replace=vi.fn();const router={replace};let query="";
vi.mock("next/navigation",()=>({useRouter:()=>router,useSearchParams:()=>new URLSearchParams(query)}));
vi.mock("@/lib/auth/client",()=>({createClient:()=>({auth:{getSession:vi.fn().mockResolvedValue({data:{session:{access_token:"token"}}})}})}));

const admin:CurrentUser={auth_user_id:"auth-1",user_profile_id:"admin-1",role:"admin",email:"admin@example.com"};
const signal={id:"signal-1",signal_type:"pain",statement:"Teams lose time reviewing invoices.",evidence_text:"We spend ten hours every week.",claim_status:"creator_claim",confidence:"0.82",evidence_strength:"0.75",industry:"Finance",customer_type:"SMB",problem:"Manual review",solution:"AI document review",observed_at:"2026-09-01T00:00:00Z",source_type:"youtube_video"};
const source={id:"opp-source",slug:"source",name:"Invoice AI",one_line_thesis:"Automate invoice review",industry:"Finance",customer_type:"SMB",problem:"Manual invoices",solution:"Document AI",market_stage:"emerging",first_detected_at:"2026-08-01T00:00:00Z",last_activity_at:"2026-09-01T00:00:00Z"};
const target={...source,id:"opp-target",slug:"target",name:"Accounts Payable Copilot",one_line_thesis:"Canonical AP automation"};
const candidate3={...source,id:"opp-third",slug:"third",name:"Finance Workflow AI"};
const activationReadiness={opportunity_id:source.id,overall:"ready" as const,recommendation:"publish" as const,checks:Object.fromEntries(["supporting_evidence","scope_clear","commercial_definition","duplicate_risk","source_diversity","contradiction_quality"].map(name=>[name,{status:name==="contradiction_quality"?"warning" as const:"pass" as const,message:`${name} result`,supporting_metrics:{}}])),metrics:{active_signal_count:4,distinct_video_count:2,distinct_channel_count:2,latest_score:"42",confidence_score:"68",hype_risk:"31",momentum_7d:"55",first_detected_at:source.first_detected_at,last_activity_at:source.last_activity_at},duplicate_candidates:[]};
function task(overrides:Partial<ReviewTask>={}):ReviewTask{return {id:"review-1",review_type:"signal_validation",target_type:"signal",target_id:"signal-1",status:"pending",priority:0.82,assigned_to:null,resolved_by:null,decision:null,decision_notes:null,context:{signal},created_at:"2026-09-04T00:00:00Z",updated_at:"2026-09-04T00:00:00Z",resolved_at:null,...overrides}}
function workflow(review:ReviewTask,decision:ReviewWorkflowResult["decision"],status:ReviewWorkflowResult["status"]="resolved"):ReviewWorkflowResult{return {review_task_id:review.id,review_type:review.review_type,previous_status:review.status,status,decision,target_type:review.target_type,target_id:review.target_id,assigned_to:"admin-1",resolved_by:status==="resolved"?"admin-1":null,resolved_at:status==="resolved"?"2026-09-05T00:00:00Z":null,side_effects:decision==="approve"?{signal_status:"active"}:{}}}
function json(body:unknown,status=200,requestId?:string){return Promise.resolve(new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json",...(requestId?{"X-Request-ID":requestId}:{})}}))}
function mockApi(review=task(),options:{user?:CurrentUser;queue?:ReviewTask[];claimStatus?:number;decisionStatus?:number;requestId?:string}={}){const queue=options.queue??[review];vi.stubGlobal("fetch",vi.fn().mockImplementation((input:RequestInfo|URL,init?:RequestInit)=>{const url=String(input);if(url.endsWith("/auth/me"))return json(options.user??admin);if(url.includes(`/admin/reviews/${review.id}/claim`))return options.claimStatus?json({detail:"Claim conflict"},options.claimStatus,options.requestId):json(workflow(review,null,"in_review"));if(url.includes(`/admin/reviews/${review.id}/decision`))return options.decisionStatus?json({detail:"Invalid decision"},options.decisionStatus,options.requestId):json(workflow(review,JSON.parse(String(init?.body)).decision,JSON.parse(String(init?.body)).decision==="defer"?"pending":"resolved"));if(url.endsWith(`/admin/reviews/${review.id}`))return json(review);if(url.includes("/admin/reviews"))return json({items:queue,offset:0,limit:25});return json({detail:"Not found"},404)}))}

describe("Admin review workspace",()=>{
  beforeEach(()=>{query="";replace.mockReset();mockApi()});

  it("shows semantic warning and blocks invalid approval",async()=>{
    query="selected=review-1";
    mockApi(task({status:"in_review",assigned_to:"admin-1",context:{signal:{...signal,semantic_status:"invalid_semantic",actor_role:"affiliate_referrer",evidence_role:"creator_monetization",guardrail_reason_code:"affiliate_revenue_not_product_revenue"}}}));
    render(<ReviewWorkspace/>);
    expect(await screen.findByText(/语义无效/)).toHaveTextContent("创作者变现");
    expect(screen.getByText("affiliate_revenue_not_product_revenue")).toBeInTheDocument();
    expect(screen.getByRole("button",{name:"Approve"})).toBeDisabled();
    expect(screen.getByRole("button",{name:"Reject"})).not.toBeDisabled();
  });
  it("loads the admin queue with backend ordering and default pending filter",async()=>{render(<ReviewWorkspace/>);expect(screen.getByLabelText("正在加载审核队列")).toBeInTheDocument();expect(await screen.findByText("Signal validation")).toBeInTheDocument();const listUrl=vi.mocked(fetch).mock.calls.map(call=>String(call[0])).find(url=>url.includes("/admin/reviews?"));expect(listUrl).toContain("status=pending");expect(screen.getByText(/priority 0.82/)).toBeInTheDocument()});
  it("blocks a non-admin even when the client route is reached",async()=>{mockApi(task(),{user:{...admin,role:"user"}});render(<ReviewWorkspace/>);expect(await screen.findByRole("alert")).toHaveTextContent("没有访问审核工作台的权限")});
  it("preserves queue filters and selection in URL",async()=>{render(<ReviewWorkspace/>);await screen.findByText("Signal validation");await userEvent.selectOptions(screen.getByLabelText("Status"),"in_review");await userEvent.selectOptions(screen.getByLabelText("Review type"),"quality_review");await userEvent.click(screen.getByRole("button",{name:"应用筛选"}));expect(replace).toHaveBeenCalledWith("/admin/review?status=in_review&review_type=quality_review");fireEvent.click(screen.getByRole("button",{name:/Signal validation/}));expect(replace).toHaveBeenLastCalledWith("/admin/review?selected=review-1")});
  it("loads selected signal detail and claims a pending task",async()=>{query="selected=review-1";render(<ReviewWorkspace/>);expect(await screen.findByText(signal.statement)).toBeInTheDocument();expect(screen.getByText(signal.evidence_text)).toBeInTheDocument();expect(screen.getByText("Unassigned")).toBeInTheDocument();await userEvent.click(screen.getByRole("button",{name:"Claim Review"}));await waitFor(()=>expect(vi.mocked(fetch).mock.calls.some(call=>String(call[0]).endsWith("/claim"))).toBe(true));expect(await screen.findByRole("status")).toHaveTextContent("Review claimed")});
  it("shows assignment conflicts with request IDs",async()=>{query="selected=review-1";mockApi(task(),{claimStatus:409,requestId:"req-claim"});render(<ReviewWorkspace/>);await userEvent.click(await screen.findByRole("button",{name:"Claim Review"}));expect(await screen.findByRole("alert")).toHaveTextContent("changed while you were working");expect(screen.getByRole("alert")).toHaveTextContent("req-claim")});
  it.each(["approve","reject","ignore","defer"] as const)("sends centralized %s signal decision with notes",async(decision)=>{const claimed=task({status:"in_review",assigned_to:"admin-1"});query="selected=review-1";mockApi(claimed);render(<ReviewWorkspace/>);await screen.findByText(signal.statement);await userEvent.type(screen.getByLabelText("Decision notes"),"Human checked");await userEvent.click(screen.getByRole("button",{name:decision==="approve"?"Approve":decision[0].toUpperCase()+decision.slice(1)}));await waitFor(()=>{const call=vi.mocked(fetch).mock.calls.find(([url])=>String(url).endsWith("/decision"));expect(JSON.parse(String(call?.[1]?.body))).toMatchObject({decision,decision_notes:"Human checked"})});if(decision==="defer")expect(await screen.findByRole("status")).toHaveTextContent("Review deferred")});
  it("renders match/create proposal and bounded candidates",async()=>{const match=task({review_type:"opportunity_match",status:"in_review",assigned_to:"admin-1",context:{signal,reason:"low confidence",model_action:"MATCH",proposed_opportunity_id:target.id,candidates:[source,target,candidate3]}});query="selected=review-1";mockApi(match);render(<ReviewWorkspace/>);expect(await screen.findByText("AI proposal")).toBeInTheDocument();expect(screen.getByText("low confidence")).toBeInTheDocument();expect(screen.getAllByText(target.name).length).toBeGreaterThan(0);expect(screen.getAllByText(candidate3.name).length).toBeGreaterThan(0);expect(screen.getByRole("button",{name:"Create New"})).toBeInTheDocument()});
  it("represents creation, hype, and quality reviews without editable score or stage controls",async()=>{for(const reviewType of ["opportunity_creation","hype_review","quality_review"] as const){cleanup();const review=task({review_type:reviewType,status:"in_review",assigned_to:"admin-1",context:{signal,reason:"Needs a human check",model_action:"REVIEW",candidates:reviewType==="opportunity_creation"?[target]:undefined}});query="selected=review-1";mockApi(review);render(<ReviewWorkspace/>);expect(await screen.findByText(LABEL_FOR_TEST[reviewType])).toBeInTheDocument();expect(screen.queryByLabelText(/score/i)).not.toBeInTheDocument();expect(screen.queryByLabelText(/market stage/i)).not.toBeInTheDocument()}});
  it("requires explicit merge confirmation before sending a merge",async()=>{const merge=task({review_type:"opportunity_merge",target_type:"opportunity",target_id:source.id,status:"in_review",assigned_to:"admin-1",context:{source_opportunity:source,canonical_opportunity:target,candidates:[target]}});query="selected=review-1";mockApi(merge);render(<ReviewWorkspace/>);expect(await screen.findByText("Source opportunity")).toBeInTheDocument();expect(screen.getByText("Canonical target")).toBeInTheDocument();expect(screen.getByText(/source is not deleted/i)).toBeInTheDocument();await userEvent.click(screen.getByRole("button",{name:"Merge"}));expect(screen.getByRole("dialog")).toHaveTextContent(`Merge “${source.name}” into “${target.name}”?`);expect(vi.mocked(fetch).mock.calls.some(([url])=>String(url).endsWith("/decision"))).toBe(false);await userEvent.click(screen.getByRole("button",{name:"确认合并"}));await waitFor(()=>{const call=vi.mocked(fetch).mock.calls.find(([url])=>String(url).endsWith("/decision"));expect(JSON.parse(String(call?.[1]?.body))).toMatchObject({decision:"merge",merge_target_opportunity_id:target.id})})});
  it("shows six activation checks and informational metrics",async()=>{const activation=task({review_type:"opportunity_activation",target_type:"opportunity",target_id:source.id,status:"in_review",assigned_to:"admin-1",context:{source_opportunity:source,readiness:activationReadiness}});query="selected=review-1";mockApi(activation);render(<ReviewWorkspace/>);const heading=await screen.findByText("激活就绪度 Activation Readiness");expect(within(heading.closest("section")!).getAllByRole("listitem")).toHaveLength(6);expect(screen.getByText(/System Recommendation: Publish/)).toBeInTheDocument();expect(screen.getByText("42")).toBeInTheDocument();expect(screen.getByText("68%")).toBeInTheDocument();expect(screen.getByText(/不会自动控制发布/)).toBeInTheDocument();expect(screen.getByRole("button",{name:"Publish"})).toBeInTheDocument();expect(screen.getByRole("button",{name:"Invalid"})).toBeInTheDocument();expect(screen.queryByRole("button",{name:"Approve"})).not.toBeInTheDocument()});
  it.each([["Publish","Publish this opportunity to Radar?","确认发布","approve"],["Invalid","Mark this opportunity invalid?","确认标记无效","reject"]] as const)("requires confirmation for activation %s",async(button,title,confirm,decision)=>{const activation=task({review_type:"opportunity_activation",target_type:"opportunity",target_id:source.id,status:"in_review",assigned_to:"admin-1",context:{source_opportunity:source,readiness:activationReadiness}});query="selected=review-1";mockApi(activation);render(<ReviewWorkspace/>);await screen.findByText("激活就绪度 Activation Readiness");await userEvent.click(screen.getByRole("button",{name:button}));expect(screen.getByRole("dialog")).toHaveTextContent(title);expect(vi.mocked(fetch).mock.calls.some(([url])=>String(url).endsWith("/decision"))).toBe(false);await userEvent.click(screen.getByRole("button",{name:confirm}));await waitFor(()=>{const call=vi.mocked(fetch).mock.calls.find(([url])=>String(url).endsWith("/decision"));expect(JSON.parse(String(call?.[1]?.body))).toMatchObject({decision})})});
  it("disables resolved and other-admin decision controls",async()=>{const resolved=task({status:"resolved",assigned_to:"other",decision:"approve",resolved_by:"other",resolved_at:"2026-09-05T00:00:00Z"});query="selected=review-1";mockApi(resolved);render(<ReviewWorkspace/>);await screen.findByText(signal.statement);expect(screen.queryByLabelText("Decision notes")).not.toBeInTheDocument();expect(screen.queryByRole("button",{name:"Approve"})).not.toBeInTheDocument()});
  it("shows 422/404 safely and never exposes raw context",async()=>{const invalid=task({status:"in_review",assigned_to:"admin-1",context:{signal,reason:"safe"} as ReviewTask["context"]});(invalid.context as unknown as Record<string,unknown>).raw_output="secret raw AI";query="selected=review-1";mockApi(invalid,{decisionStatus:422,requestId:"req-validation"});render(<ReviewWorkspace/>);await screen.findByText(signal.statement);expect(screen.queryByText("secret raw AI")).not.toBeInTheDocument();await userEvent.click(screen.getByRole("button",{name:"Approve"}));expect(await screen.findByRole("alert")).toHaveTextContent("Invalid decision");expect(screen.getByRole("alert")).toHaveTextContent("req-validation")});
  it("renders invalid context safely",async()=>{const invalid=task({context:{}});query="selected=review-1";mockApi(invalid);render(<ReviewWorkspace/>);expect(await screen.findByText("No safe presentation context is available for this task.")).toBeInTheDocument()});
  it("offers a refresh after a safe 404 and keeps its request ID",async()=>{query="selected=review-1";mockApi();const original=vi.mocked(fetch).getMockImplementation();vi.mocked(fetch).mockImplementation((input,init)=>String(input).endsWith("/admin/reviews/review-1")?json({detail:"internal record detail must not leak"},404,"req-missing"):original!(input,init));render(<ReviewWorkspace/>);expect(await screen.findByRole("alert")).toHaveTextContent("Review task not found or unavailable.");expect(screen.getByRole("alert")).toHaveTextContent("req-missing");await userEvent.click(screen.getByRole("button",{name:/retry|重试/i}));await waitFor(()=>expect(vi.mocked(fetch).mock.calls.filter(([url])=>String(url).endsWith("/admin/reviews/review-1")).length).toBeGreaterThan(1))});
  it("renders an empty pending queue clearly",async()=>{mockApi(task(),{queue:[]});render(<ReviewWorkspace/>);expect(await screen.findByText("Review queue is clear.")).toBeInTheDocument()});
});

const LABEL_FOR_TEST={opportunity_creation:"Opportunity creation",hype_review:"Hype review",quality_review:"Quality review"} as const;
