import { cleanup, render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
import { BusinessCasePanel, type BusinessCaseView } from "@/components/business-case/business-case-panel";
import { ApiClient } from "@/lib/api/client";
import { LocaleProvider } from "@/lib/i18n/context";

const keys=["customer_summary","problem_summary","workflow_summary","solution_pattern","business_model_summary","pricing_summary","revenue_summary","distribution_summary","competition_summary","adoption_summary","build_complexity_summary"];
let data:BusinessCaseView; let request:ReturnType<typeof vi.fn>;
function setup(admin=true){const api={request} as unknown as ApiClient;return render(<LocaleProvider><BusinessCasePanel id="candidate" api={api} admin={admin}/></LocaleProvider>)}
beforeEach(()=>{localStorage.clear();const fields=Object.fromEntries(keys.map(k=>[k,{text:null as string|null,evidence_signal_ids:[] as string[],information_class:"unknown",support_level:"insufficient_evidence",uncertainty:"No supplied evidence"}]));fields.solution_pattern={text:"AI receptionist workflow for dental practices",evidence_signal_ids:["signal"] as never[],information_class:"editorial_synthesis",support_level:"partially_supported",uncertainty:"Vendor claims only"};data={state:"current",case:{id:"case1",version:1,status:"completed",review_status:"pending",parsed_output:{...fields,validation_gaps:["No verified revenue"]} as NonNullable<BusinessCaseView["case"]>["parsed_output"],field_metadata:{} as NonNullable<BusinessCaseView["case"]>["field_metadata"]},latest_attempt:{id:"case1",status:"completed",error_code:null},opportunity_status:"candidate",opportunity_updated_at:"2026-09-09T00:00:00Z",history:[]};request=vi.fn(async(path:string,init?:RequestInit)=>{if(init?.method==="POST")return {id:"case1",status:"queued"};if(path.includes("/evidence/"))return {items:[{evidence_id:"e",statement:"A vendor describes scheduling",evidence_text:"Quoted source",claim_status:"creator_claim",relationship_type:"supporting",source_navigation:"unavailable"}],total:1,offset:0,limit:20,has_more:false};return structuredClone(data)})});
afterEach(()=>{cleanup();vi.restoreAllMocks()});
it("renders machine synthesis, explicit unknowns and gaps without read-path mutation",async()=>{setup();expect(await screen.findByText("AI receptionist workflow for dental practices")).toBeInTheDocument();expect(screen.getByText("No verified revenue")).toBeInTheDocument();expect(screen.getAllByText("证据不足／待验证").length).toBe(10);expect(request.mock.calls.every(c=>!c[1])).toBe(true)});
it("drills through the shared evidence API",async()=>{setup();await screen.findByText("AI receptionist workflow for dental practices");await userEvent.click(screen.getByRole("button",{name:"查看证据 · 解决方案模式"}));expect(await screen.findByText("Quoted source")).toBeInTheDocument();expect(request).toHaveBeenCalledWith(expect.stringContaining("/consolidation/evidence/solution_pattern?locale=zh-CN"))});
it("refresh explicitly enqueues and reloads",async()=>{setup();await screen.findByText("AI receptionist workflow for dental practices");await userEvent.click(screen.getByRole("button",{name:"重新整理机会论证"}));expect(request).toHaveBeenCalledWith("/api/v1/admin/opportunities/candidate/consolidation",{method:"POST"});expect(await screen.findByText("整理请求已提交；完成后自动更新。")).toBeInTheDocument()});
it("accepts an edited selected field with optimistic timestamp and audit note",async()=>{setup();await screen.findByText("AI receptionist workflow for dental practices");await userEvent.click(screen.getByRole("button",{name:"采纳或编辑 · 解决方案模式"}));await userEvent.clear(screen.getByLabelText("采纳文本"));await userEvent.type(screen.getByLabelText("采纳文本"),"Human curated workflow");await userEvent.type(screen.getByLabelText("采纳说明"),"Checked source scope");await userEvent.click(screen.getByRole("button",{name:"确认采纳字段"}));await waitFor(()=>expect(request).toHaveBeenCalledWith(expect.stringContaining("/case1/accept"),expect.objectContaining({body:expect.stringContaining('"edited_text":"Human curated workflow"')})))});
it("keep current makes no mutation",async()=>{setup();await screen.findByText("AI receptionist workflow for dental practices");await userEvent.click(screen.getByRole("button",{name:"采纳或编辑 · 解决方案模式"}));await userEvent.click(screen.getByRole("button",{name:"保留当前"}));expect(request.mock.calls.every(c=>!c[1])).toBe(true)});
it("stale output is labeled historical and cannot be accepted",async()=>{data.state="stale";setup();await screen.findByText("AI receptionist workflow for dental practices");expect(screen.getByText("以下为历史版本，仅供比较，不能作为当前支持。")).toBeInTheDocument();expect(screen.queryByRole("button",{name:/采纳或编辑/})).not.toBeInTheDocument();expect(screen.getByRole("button",{name:/查看证据/})).toBeDisabled()});
it("public missing output has explicit sections and no admin controls",async()=>{data={state:"unavailable",case:null};setup(false);expect(await screen.findByText("状态: 待验证／待审核")).toBeInTheDocument();expect(screen.getAllByText("证据不足／待验证").length).toBe(11);expect(screen.queryByRole("button",{name:"重新整理机会论证"})).not.toBeInTheDocument()});
it("requires explicit confirmation before display approval",async()=>{setup();await screen.findByText("AI receptionist workflow for dental practices");await userEvent.click(screen.getByRole("button",{name:"确认此版论证可展示"}));expect(request.mock.calls.every(c=>!c[1])).toBe(true);await userEvent.click(screen.getByRole("button",{name:"确认展示"}));expect(request).toHaveBeenCalledWith(expect.stringContaining("/case1/approve"),{method:"POST"})});
it("English fixed labels preserve canonical content",async()=>{localStorage.setItem("ai-business-radar.locale","en-US");setup();expect(await screen.findByRole("heading",{name:"Opportunity business case"})).toBeInTheDocument();expect(screen.getByRole("button",{name:"Refresh business case"})).toBeInTheDocument()});
it("failed evidence fetch clears prior evidence on retry",async()=>{setup();await screen.findByText("AI receptionist workflow for dental practices");const evidenceButton=screen.getByRole("button",{name:/查看证据/});await userEvent.click(evidenceButton);await screen.findByText("Quoted source");request.mockRejectedValueOnce(new Error("offline"));await userEvent.click(evidenceButton);await screen.findByRole("alert");expect(screen.queryByText("Quoted source")).not.toBeInTheDocument()});
