import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
import { CandidateDossier, CandidateList } from "@/components/candidates/candidate-workspace";
import { LocaleProvider } from "@/lib/i18n/context";
import type { CandidateDetail, CandidateSummary } from "@/lib/api/types";
const push=vi.fn();let query="";
vi.mock("next/navigation",()=>({useRouter:()=>({push}),useSearchParams:()=>new URLSearchParams(query)}));
vi.mock("@/lib/auth/client",()=>({createClient:()=>({auth:{getSession:async()=>({data:{session:{access_token:"test-token"}}})}})}));
const stamp="2026-09-09T00:00:00Z";
const summary:CandidateSummary={id:"candidate",name:"Orbital custody assistant",one_line_thesis:null,industry:null,customer_type:"Labs",industry_taxonomy:null,customer_taxonomy:null,evidence_summary:{active_signal_count:2,supporting_signal_count:2,distinct_video_count:2,distinct_channel_count:2,pain_signal_count:2,demand_signal_count:0,purchase_intent_signal_count:0,revenue_signal_count:0},semantic_warning_count:1,readiness:{opportunity_id:"candidate",overall:"ready",recommendation:"publish",checks:{supporting_evidence:{status:"pass",message:"Active supporting evidence exists.",supporting_metrics:{active_signal_count:2}}},metrics:{active_signal_count:2,distinct_video_count:2,distinct_channel_count:2,latest_score:null,confidence_score:null,hype_risk:null,momentum_7d:null,first_detected_at:stamp,last_activity_at:stamp},duplicate_candidates:[]},activation_review:null,review_state:"none",last_activity_at:stamp,score_at:null,trend_at:null,score_freshness:"pending",trend_freshness:"pending"};
let detail:CandidateDetail;
function reply(value:unknown,status=200){return Promise.resolve(new Response(JSON.stringify(value),{status,headers:{"Content-Type":"application/json"}}))}
function setup(){vi.stubGlobal("fetch",vi.fn((url:RequestInfo|URL,init?:RequestInit)=>{const path=String(url);if(path.includes("/auth/me"))return reply({user_profile_id:"admin",role:"admin"});if(path.includes("/taxonomy/"))return reply([{code:"lab",label:"Laboratories"}]);if(path.includes("/evidence"))return reply({items:[],total:0,offset:0,limit:20,has_more:false});if(path.endsWith("/activation-review")){detail.summary.activation_review={id:"review",status:"pending",assigned_to:null,created_at:stamp,decision:null,decision_notes:null};detail.summary.review_state="pending";return reply({review_task_id:"review",created:true})}if(path.endsWith("/claim")){detail.summary.activation_review!.status="in_review";detail.summary.activation_review!.assigned_to="admin";return reply({})}if(path.endsWith("/decision")){const body=JSON.parse(String(init?.body));if(body.decision==="approve")detail.opportunity.status="active";if(body.decision==="reject")detail.opportunity.status="rejected";if(body.decision!=="defer")detail.summary.activation_review=null;return reply({})}if(path.includes("/candidates/candidate")){if(init?.method==="PATCH"){const body=JSON.parse(String(init.body));Object.assign(detail.opportunity,body)}return reply(detail)}if(path.includes("/candidates"))return reply({items:[detail.summary],total:1,offset:0,limit:20,has_more:false,counts:{total:1,ready:1,needs_review:0,not_ready:0,under_review:0,deferred:0}});if(path.endsWith("/opportunities/candidate"))return reply({opportunity:detail.opportunity});return reply({},404)}))}
beforeEach(()=>{query="";push.mockReset();localStorage.clear();detail={summary:structuredClone(summary),opportunity:{id:"candidate",slug:"candidate",name:summary.name,one_line_thesis:null,industry:null,sub_industry:null,customer_type:"Labs",problem:"Handoffs",solution:"Tracking",business_model:null,primary_technology:null,typical_price_min:null,typical_price_max:null,typical_price_currency:null,typical_price_period:null,competition_level:null,build_difficulty:null,sales_difficulty:null,market_stage:"unknown",first_detected_at:stamp,last_activity_at:stamp,updated_at:stamp,status:"candidate"},revisions:[],review_history:[],legacy_reviews:[],translation_state:"pending",history_has_more:false};setup()});
afterEach(()=>cleanup());
it("renders candidate navigation, counts and server filters",async()=>{render(<CandidateList/>);expect(await screen.findByRole("link",{name:summary.name})).toHaveAttribute("href","/admin/review/candidates/candidate");await userEvent.type(screen.getByLabelText("搜索"),"orbital");await userEvent.selectOptions(screen.getByLabelText("行业"),"lab");await userEvent.click(screen.getByRole("button",{name:"应用筛选"}));expect(push).toHaveBeenCalledWith(expect.stringContaining("q=orbital"));expect(push).toHaveBeenCalledWith(expect.stringContaining("industry_code=lab"))});
it("saves draft without invoking publication or submission",async()=>{render(<CandidateDossier id="candidate"/>);await screen.findByRole("heading",{name:summary.name});const thesis=screen.getByLabelText(/一句话论点/);await userEvent.type(thesis,"Track custody");await userEvent.click(screen.getByRole("button",{name:"保存草稿"}));await screen.findByText("草稿已保存；未发布。");const calls=vi.mocked(fetch).mock.calls;expect(calls.some(([u])=>String(u).endsWith("/decision"))).toBe(false);expect(calls.some(([u])=>String(u).endsWith("/activation-review"))).toBe(false);expect(calls.find(([,i])=>i?.method==="PATCH")?.[1]?.body).toContain('"expected_updated_at"')});
it("submits once and switches to View activation review",async()=>{render(<CandidateDossier id="candidate"/>);const submit=await screen.findByRole("button",{name:"提交发布审核"});fireEvent.click(submit);fireEvent.click(submit);expect(await screen.findByRole("link",{name:"查看发布审核"})).toBeInTheDocument();expect(vi.mocked(fetch).mock.calls.filter(([u])=>String(u).endsWith("/activation-review"))).toHaveLength(1);expect(screen.queryByRole("button",{name:"提交发布审核"})).not.toBeInTheDocument()});
it.each([["发布","approve","active"],["标记无效","reject","rejected"]])("confirms %s through existing review API",async(name,decision,status)=>{detail.summary.activation_review={id:"review",status:"in_review",assigned_to:"admin",created_at:stamp,decision:null,decision_notes:null};render(<CandidateDossier id="candidate"/>);await userEvent.click(await screen.findByRole("button",{name}));expect(screen.getByRole("dialog")).toBeInTheDocument();expect(vi.mocked(fetch).mock.calls.some(([u])=>String(u).endsWith("/decision"))).toBe(false);await userEvent.click(screen.getByRole("button",{name:"确认决定"}));await waitFor(()=>expect(detail.opportunity.status).toBe(status));const body=vi.mocked(fetch).mock.calls.find(([u])=>String(u).endsWith("/decision"))?.[1]?.body;expect(JSON.parse(String(body)).decision).toBe(decision);if(status==="active")expect(await screen.findByRole("link",{name:"查看前台机会"})).toHaveAttribute("href","/opportunities/candidate")});
it("Defer retains non-public candidate",async()=>{detail.summary.activation_review={id:"review",status:"in_review",assigned_to:"admin",created_at:stamp,decision:null,decision_notes:null};render(<CandidateDossier id="candidate"/>);await userEvent.click(await screen.findByRole("button",{name:"暂缓"}));expect(await screen.findByText("已暂缓，候选保持非公开。")).toBeInTheDocument();expect(detail.opportunity.status).toBe("candidate")});
it("blocks publication on hard blockers",async()=>{detail.summary.readiness.overall="not_ready";detail.summary.activation_review={id:"review",status:"in_review",assigned_to:"admin",created_at:stamp,decision:null,decision_notes:null};render(<CandidateDossier id="candidate"/>);expect(await screen.findByRole("button",{name:"发布"})).toBeDisabled()});
it("explains excluded evidence separately",async()=>{render(<CandidateDossier id="candidate"/>);await userEvent.click(await screen.findByRole("button",{name:"排除与待审核证据"}));expect(await screen.findByText(/不计入有效支持/)).toBeInTheDocument();await waitFor(()=>expect(vi.mocked(fetch).mock.calls.some(([u])=>String(u).includes("excluded=true"))).toBe(true))});
it("renders English fixed labels",async()=>{localStorage.setItem("ai-business-radar.locale","en-US");render(<LocaleProvider><CandidateDossier id="candidate"/></LocaleProvider>);expect(await screen.findByRole("button",{name:"Save draft"})).toBeInTheDocument();expect(screen.getByRole("button",{name:"Submit for activation review"})).toBeInTheDocument()});
it("shows retry on transport failure",async()=>{vi.stubGlobal("fetch",vi.fn().mockRejectedValue(new TypeError("Failed to fetch")));render(<CandidateList/>);expect(await screen.findByRole("alert")).toHaveTextContent("请求未完成");expect(screen.getByRole("button",{name:"重试"})).toBeInTheDocument()});
it("never displays stale effective evidence under an excluded tab after a failed request",async()=>{const original=vi.mocked(fetch).getMockImplementation()!;vi.mocked(fetch).mockImplementation((url,init)=>{if(String(url).includes("/evidence")){if(String(url).includes("excluded=true"))return Promise.reject(new TypeError("Failed to fetch"));return reply({items:[{evidence_id:"e1",evidence_kind:"linked_signal",signal_id:"s1",signal_type:"pain",evidence_type:"pain",statement:"Effective-only observation",summary:"Effective-only observation",evidence_text:null,claim_status:"unknown",relationship_type:"supporting",source_type:"video",observed_at:stamp,semantic_status:"current",signal_status:"active",source_url:null,source_navigation:"unavailable"}],total:1,offset:0,limit:20,has_more:false})}return original(url,init)});render(<CandidateDossier id="candidate"/>);expect(await screen.findByText("Effective-only observation")).toBeInTheDocument();await userEvent.click(screen.getByRole("button",{name:"排除与待审核证据"}));expect(await screen.findByRole("alert")).toBeInTheDocument();expect(screen.queryByText("Effective-only observation")).not.toBeInTheDocument();expect(screen.getByText("证据加载未完成，请重试。")).toBeInTheDocument()});
it("does not label an already published dossier as blocked for candidate activation",async()=>{detail.opportunity.status="active";detail.summary.readiness.overall="not_ready";render(<CandidateDossier id="candidate"/>);expect(await screen.findByText(/当前记录不再处于候选状态/)).toBeInTheDocument();expect(screen.queryByText("发布就绪度: 存在发布阻碍")).not.toBeInTheDocument();expect(screen.queryByRole("button",{name:"保存草稿"})).not.toBeInTheDocument()});
