import {render,screen,waitFor} from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import {describe,expect,it,vi} from "vitest";
import {DiscoveryConsole} from "@/components/discovery/discovery-console";
vi.mock("@/lib/auth/client",()=>({createClient:()=>({auth:{getSession:async()=>({data:{session:{access_token:"token"}}})}})}));
const run={id:"run-1",topic_id:"topic-1",query_id:"query-1",query_text:"AI dental receptionist",trigger_type:"manual",status:"completed",started_at:"2026-09-08T00:00:00Z",completed_at:"2026-09-08T00:01:00Z",videos_discovered:3,quota_estimate:100,error_code:null,error_message_safe:null,worker_message_id:"message-1"};
const topic={id:"topic-1",name:"AI Dental Front Desk",description:"Dental research",status:"paused",default_schedule:"manual",default_max_videos:5,default_max_pages:1,default_max_comments_per_video:10,query_count:2,last_run_at:null,next_run_at:null,latest_run:run};
const json=(body:unknown,status=200)=>Promise.resolve(new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json"}}));
function mockFetch(runResponse:unknown=[{...run,status:"queued"}]){vi.stubGlobal("fetch",vi.fn().mockImplementation((input:RequestInfo|URL)=>{const url=String(input);if(url.endsWith("system-status"))return json({redis:"configured",worker:"unknown",scheduler:"configured",youtube_api:"configured",openai_api:"configured"});if(url.includes("/runs"))return json({items:[run],total:1,page:1,page_size:100});if(url.includes("/topics/topic-1/run"))return json(runResponse,Array.isArray(runResponse)?202:409);return json([topic])}))}
describe("Discovery Console",()=>{it("shows scoped queuing state, pointer affordance and refreshes",async()=>{let release:(value:Response)=>void=()=>{};mockFetch();const original=vi.mocked(fetch).getMockImplementation()!;vi.mocked(fetch).mockImplementation((input,init)=>String(input).includes("/topics/topic-1/run")?new Promise(resolve=>{release=resolve}):original(input,init));render(<DiscoveryConsole/>);await screen.findByText("AI Dental Front Desk");const button=screen.getByRole("button",{name:"Run Now"});expect(button).toHaveClass("cursor-pointer");await userEvent.click(button);expect(screen.getByRole("button",{name:"排队中…"})).toBeDisabled();release(await json([{...run,status:"queued"}],202));expect(await screen.findByText("发现任务已排队。")).toBeInTheDocument();await waitFor(()=>expect(vi.mocked(fetch).mock.calls.filter(([url])=>String(url).includes("/topics")).length).toBeGreaterThan(1))});it("renders duplicate conflict as domain status and refreshes",async()=>{mockFetch({error:{message:"Discovery query already queued or running"}});render(<DiscoveryConsole/>);await screen.findByText("AI Dental Front Desk");await userEvent.click(screen.getByRole("button",{name:"Run Now"}));expect(await screen.findByText("该发现任务已在队列中或正在运行。")).toBeInTheDocument()});it("supports multiple query editing",async()=>{mockFetch();render(<DiscoveryConsole/>);await screen.findByText("AI Dental Front Desk");await userEvent.click(screen.getByRole("button",{name:"+ Add query"}));expect(screen.getByLabelText("Query 2")).toBeInTheDocument()})});
