import {fireEvent,render,screen,waitFor} from "@testing-library/react";
import {beforeEach,describe,expect,it,vi} from "vitest";
import {OpportunityLibrary} from "@/components/opportunities/opportunity-library";

const replace=vi.fn();
vi.mock("next/navigation",()=>({useRouter:()=>({replace}),useSearchParams:()=>new URLSearchParams("sort=score_desc&page_size=50")}));
vi.mock("@/lib/auth/client",()=>({createClient:()=>({auth:{getSession:vi.fn().mockResolvedValue({data:{session:{access_token:"token"}}})}})}));
const item={id:"opp-1",slug:"dental-ai",name:"牙科 AI 前台",one_line_thesis:"自动接听并筛选牙科诊所来电。",industry:"Dental",sub_industry:null,customer_type:"SMB",industry_taxonomy:{code:"healthcare.dental",label:"牙科"},customer_taxonomy:{code:"smb",label:"中小企业"},business_model:"saas",market_stage:"emerging",competition_level:null,build_difficulty:null,sales_difficulty:null,opportunity_score:"78",confidence_score:"82",hype_risk_score:"21",trend:{window_type:"7d",period_start:"2026-09-01",period_end:"2026-09-08",aggregation_version:"trend-v001",video_count:3,new_video_count:2,unique_channel_count:2,total_views:1000,comment_count:10,pain_signal_count:1,demand_signal_count:2,purchase_intent_signal_count:1,revenue_signal_count:0,competitor_signal_count:0,momentum_score:"64"},first_detected_at:"2026-08-01T00:00:00Z",last_activity_at:"2026-09-08T00:00:00Z",evidence_summary:{active_signal_count:4,distinct_video_count:3,distinct_channel_count:2,pain_signal_count:1,demand_signal_count:2,purchase_intent_signal_count:1,revenue_signal_count:0},watchlisted:false};

describe("Opportunity Library",()=>{beforeEach(()=>{replace.mockReset();vi.stubGlobal("fetch",vi.fn().mockImplementation(()=>Promise.resolve(new Response(JSON.stringify({items:[item],total:1,page:1,page_size:50,total_pages:1}),{status:200,headers:{"Content-Type":"application/json"}}))))});it("loads the paginated library and preserves URL-driven controls",async()=>{render(<OpportunityLibrary/>);expect(await screen.findAllByText("牙科 AI 前台")).toHaveLength(2);expect(screen.getAllByText(/3 videos/).length).toBeGreaterThan(0);await waitFor(()=>expect(fetch).toHaveBeenCalledWith(expect.stringContaining("sort=score_desc"),expect.anything()));fireEvent.change(screen.getByLabelText("排序方式"),{target:{value:"name_asc"}});expect(replace).toHaveBeenCalledWith(expect.stringContaining("sort=name_asc"))});});
