import { fireEvent,render,screen,waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { beforeEach,describe,expect,it,vi } from "vitest";
import { SignalsFeed } from "@/components/signals/signals-feed";
import { WatchlistPage } from "@/components/watchlist/watchlist-page";
import { WatchlistButton } from "@/components/watchlist/watchlist-button";
import type { SignalFeedItem,WatchlistItem } from "@/lib/api/types";

const replace=vi.fn();const router={replace};let query="";
vi.mock("next/navigation",()=>({useRouter:()=>router,useSearchParams:()=>new URLSearchParams(query)}));
vi.mock("@/lib/auth/client",()=>({createClient:()=>({auth:{getSession:vi.fn().mockResolvedValue({data:{session:{access_token:"token"}}})}})}));
function response(body:unknown,status=200,id?:string){return Promise.resolve({ok:status>=200&&status<300,status,headers:new Headers(id?{"X-Request-ID":id}:{}),json:async()=>body} as Response)}
const signal:SignalFeedItem={id:"signal-1",signal_type:"workflow",statement:"团队每周花数小时核对发票。",evidence_text:"我们仍逐张人工核对发票。",original_statement:"Teams lose hours reconciling invoices.",original_evidence_text:"We review every invoice by hand.",statement_localized:true,evidence_localized:true,localization_stale:false,industry:"Finance",customer_type:"SMB",claim_status:"creator_claim",confidence:"0.82",evidence_strength:"0.71",observed_at:"2026-09-04T08:00:00Z",source_type:"video",source_url:"https://www.youtube.com/watch?v=abcdefghijk",source_navigation:"video",video_title:"Invoice automation field report",channel_name:"Creative World Prime",opportunity_ids:["opp-1"],opportunities:[{id:"opp-1",slug:"invoice-ai",name:"Invoice AI"}]};
const watched:WatchlistItem={opportunity:{id:"opp-1",slug:"invoice-ai",name:"Invoice AI",one_line_thesis:"Automate invoice operations",industry:"Finance",market_stage:"accelerating"},opportunity_score:"74",confidence_score:"78",hype_risk_score:"22",momentum_score:"64",added_at:"2026-09-04T00:00:00Z"};

describe("Signals and watchlist UI",()=>{beforeEach(()=>{query="";replace.mockReset();vi.stubGlobal("fetch",vi.fn().mockResolvedValue(new Response("[]",{headers:{"Content-Type":"application/json"}})))});
  it("loads and renders a private-safe chronological signal feed",async()=>{vi.stubGlobal("fetch",vi.fn().mockReturnValue(response([{...signal,comment_author:"private",provider_id:"hidden"}])));render(<SignalsFeed/>);expect(screen.getByLabelText("正在加载商业信号")).toBeInTheDocument();expect(await screen.findByText(signal.statement)).toBeInTheDocument();expect(screen.getByText(signal.evidence_text!)).toBeInTheDocument();expect(screen.getAllByText("工作流").length).toBeGreaterThan(0);expect(screen.getByText("创作者声明")).toBeInTheDocument();expect(screen.getByText("82%")).toBeInTheDocument();expect(screen.getByText("71%")).toBeInTheDocument();expect(screen.getByRole("link",{name:/Invoice automation field report/})).toBeInTheDocument();expect(screen.getByText(/Creative World Prime/)).toBeInTheDocument();expect(screen.getByRole("link",{name:"Invoice AI"})).toHaveAttribute("href","/opportunities/invoice-ai");expect(screen.queryByText("private")).not.toBeInTheDocument();expect(screen.queryByText("hidden")).not.toBeInTheDocument()});
  it("applies URL opportunity context and uses source navigation",async()=>{query="opportunity_id=opp-1";vi.stubGlobal("fetch",vi.fn().mockReturnValue(response([signal])));render(<SignalsFeed/>);await screen.findByText(signal.statement);expect(String(vi.mocked(fetch).mock.calls[0][0])).toContain("opportunity_id=opp-1");expect(screen.getByText(/当前机会/)).toBeInTheDocument();expect(screen.getByRole("link",{name:/Invoice automation field report/})).toHaveAttribute("href",signal.source_url)});
  it("hides the evidence-strength block when the value is null",async()=>{vi.stubGlobal("fetch",vi.fn().mockReturnValue(response([{...signal,evidence_strength:null}])));render(<SignalsFeed/>);await screen.findByText(signal.statement);expect(screen.getByText("82%")).toBeInTheDocument();expect(screen.queryByText("证据强度")).not.toBeInTheDocument()});
  it("sends supported filters and resets pagination",async()=>{query="offset=50";render(<SignalsFeed/>);await waitFor(()=>expect(fetch).toHaveBeenCalled());await userEvent.selectOptions(screen.getByLabelText("信号类型"),"purchase_intent");await userEvent.type(screen.getByLabelText("行业"),"Finance");await userEvent.type(screen.getByLabelText("客户"),"SMB");fireEvent.change(screen.getByLabelText("观察时间晚于"),{target:{value:"2026-09-01"}});await userEvent.type(screen.getByLabelText("机会 ID"),"opp-1");await userEvent.click(screen.getByRole("button",{name:"应用筛选"}));const url=replace.mock.calls.at(-1)?.[0];expect(url).toContain("signal_type=purchase_intent");expect(url).toContain("industry=Finance");expect(url).toContain("customer_type=SMB");expect(url).toContain("observed_after=2026-09-01");expect(url).toContain("opportunity_id=opp-1");expect(url).not.toContain("offset")});
  it("keeps translated evidence distinct and reveals the original on demand",async()=>{vi.stubGlobal("fetch",vi.fn().mockReturnValue(response([signal])));render(<SignalsFeed/>);await screen.findByText("译文证据");expect(screen.queryByText(signal.original_evidence_text!)).not.toBeInTheDocument();await userEvent.click(screen.getByRole("button",{name:"查看原文"}));expect(screen.getByText(signal.original_evidence_text!)).toBeInTheDocument();expect(screen.getAllByText("行业").length).toBeGreaterThan(0);expect(screen.getAllByText("客户").length).toBeGreaterThan(0);expect(screen.getByText("声明类型")).toBeInTheDocument()});
  it("paginates a full signal page and handles null confidence",async()=>{vi.stubGlobal("fetch",vi.fn().mockReturnValue(response(Array.from({length:25},(_,index)=>({...signal,id:`s-${index}`,statement:`Signal ${index}`,confidence:index?"0.5":null})))));render(<SignalsFeed/>);await screen.findByText("Signal 0");expect(screen.getAllByText("—").length).toBeGreaterThan(0);await userEvent.click(screen.getByRole("button",{name:/下一页/}));expect(replace).toHaveBeenCalledWith("/signals?offset=25")});
  it("distinguishes empty and filtered-empty signals",async()=>{const first=render(<SignalsFeed/>);expect(await screen.findByText("目前还没有已激活的商业信号")).toBeInTheDocument();first.unmount();query="industry=None";render(<SignalsFeed/>);expect(await screen.findByText("没有符合筛选条件的信号")).toBeInTheDocument()});
  it("shows signal API request IDs",async()=>{vi.stubGlobal("fetch",vi.fn().mockReturnValue(response({error:{message:"Signals unavailable"}},500,"req-signals")));render(<SignalsFeed/>);expect(await screen.findByRole("alert")).toHaveTextContent("req-signals")});
  it("loads a product-ready watchlist without per-item requests",async()=>{vi.stubGlobal("fetch",vi.fn().mockReturnValue(response({items:[watched]})));render(<WatchlistPage/>);expect(screen.getByLabelText("正在加载关注列表")).toBeInTheDocument();expect(await screen.findAllByText("Invoice AI")).toHaveLength(2);expect(screen.getAllByText("74").length).toBeGreaterThan(0);expect(screen.getAllByText("64").length).toBeGreaterThan(0);expect(screen.getAllByRole("link",{name:"Invoice AI"})[0]).toHaveAttribute("href","/opportunities/invoice-ai");expect(vi.mocked(fetch).mock.calls.every(([url])=>String(url).endsWith("/watchlist"))).toBe(true)});
  it("renders the watchlist empty state",async()=>{vi.stubGlobal("fetch",vi.fn().mockReturnValue(response({items:[]})));render(<WatchlistPage/>);expect(await screen.findByText("Your watchlist is empty.")).toBeInTheDocument();expect(screen.getByRole("link",{name:"Explore Radar"})).toHaveAttribute("href","/radar")});
  it("adds and removes through one shared, duplicate-safe control",async()=>{vi.stubGlobal("fetch",vi.fn().mockImplementation((_input,init?:RequestInit)=>response({opportunity_id:"opp-1",watchlisted:init?.method==="POST",added_at:null})));const view=render(<WatchlistButton opportunityId="opp-1" initialWatchlisted={false}/>);await userEvent.click(screen.getByRole("button",{name:"加入关注列表"}));expect(await screen.findByRole("button",{name:"从关注列表移除"})).toBeInTheDocument();expect(screen.getByRole("status")).toHaveTextContent("已加入");await userEvent.click(screen.getByRole("button",{name:"从关注列表移除"}));expect(await screen.findByRole("button",{name:"加入关注列表"})).toBeInTheDocument();expect(vi.mocked(fetch).mock.calls.map(call=>call[1]?.method)).toEqual(["POST","DELETE"]);view.unmount()});
  it("disables duplicate watchlist submission and surfaces failures",async()=>{let release:(value:Response)=>void=()=>{};vi.stubGlobal("fetch",vi.fn().mockReturnValue(new Promise<Response>(resolve=>{release=resolve})));render(<WatchlistButton opportunityId="opp-1" initialWatchlisted={false}/>);const button=screen.getByRole("button",{name:"加入关注列表"});await userEvent.click(button);expect(screen.getByRole("button",{name:"正在更新关注列表"})).toBeDisabled();fireEvent.click(screen.getByRole("button",{name:"正在更新关注列表"}));expect(fetch).toHaveBeenCalledTimes(1);release(await response({error:{message:"Write failed"}},500,"req-watch"));expect(await screen.findByRole("status")).toHaveTextContent("req-watch")});
  it("removes a watchlist row only after backend success",async()=>{vi.stubGlobal("fetch",vi.fn().mockImplementation((input,init?:RequestInit)=>String(input).endsWith("/watchlist")?response({items:[watched]}):response({opportunity_id:"opp-1",watchlisted:false,added_at:null},init?.method==="DELETE"?200:500)));render(<WatchlistPage/>);await screen.findAllByText("Invoice AI");await userEvent.click(screen.getAllByRole("button",{name:"从关注列表移除"})[0]);await waitFor(()=>expect(screen.queryByText("Invoice AI")).not.toBeInTheDocument())});
});
