"use client";
/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
import {FormEvent,useEffect,useRef,useState} from "react";
import {ApiClient,ApiError} from "@/lib/api/client";
import {createClient} from "@/lib/auth/client";
import type {DiscoverySystemStatus,DiscoveryTopic,DiscoveryTopicRun} from "@/lib/api/types";
import {useI18n} from "@/lib/i18n/context";
import {EmptyState,ErrorState} from "@/components/states/states";
import {PageHeader} from "@/components/ui/primitives";

const button="cursor-pointer rounded-md border px-3 py-2 text-sm disabled:cursor-not-allowed disabled:opacity-45";
const active=(run:DiscoveryTopicRun|null|undefined)=>run?.status==="queued"||run?.status==="running"||run?.intelligence_status==="queued"||run?.intelligence_status==="processing";
const locale="zh-CN";

export function DiscoveryConsole(){
 const {locale}=useI18n(); const [topics,setTopics]=useState<DiscoveryTopic[]>([]); const [system,setSystem]=useState<DiscoverySystemStatus|null>(null); const [batches,setBatches]=useState<Record<string,DiscoveryTopicRun>>({}); const [loading,setLoading]=useState(true); const [error,setError]=useState<ApiError|null>(null); const [notice,setNotice]=useState<string|null>(null); const [pending,setPending]=useState<Record<string,string>>({}); const [queries,setQueries]=useState([""]); const mounted=useRef(true);
 const api=async()=>{const {data:{session}}=await createClient().auth.getSession();return new ApiClient(async()=>session?.access_token??null)};
 const load=async(showLoading=false)=>{if(showLoading)setLoading(true);try{const client=await api();const [items,status]=await Promise.all([client.listDiscoveryTopics(),client.getDiscoveryStatus()]);if(mounted.current){setTopics(items);setBatches(Object.fromEntries(items.filter(x=>x.current_topic_run).map(x=>[x.id,x.current_topic_run!] as const)));setSystem(status);setError(null)}}catch(e){if(mounted.current)setError(e instanceof ApiError?e:new ApiError(0,"无法加载数据发现控制台"))}finally{if(mounted.current)setLoading(false)}};
 useEffect(()=>{mounted.current=true;void load(true);return()=>{mounted.current=false}},[]);
 const activeIds=Object.values(batches).filter(active).map(batch=>batch.id).sort().join(",");
 useEffect(()=>{if(!activeIds)return;const poll=async()=>{try{const client=await api();const updates=await Promise.all(activeIds.split(",").map(id=>client.getDiscoveryTopicRun(id)));if(!mounted.current)return;setBatches(current=>{const next={...current};for(const batch of updates)next[batch.topic_id]=batch;return next});for(const batch of updates.filter(item=>!active(item)))setNotice(locale==="zh-CN"?`处理已结束：发现 ${batch.status}，情报 ${batch.intelligence_status}`:`Processing finished: discovery ${batch.status}, intelligence ${batch.intelligence_status}`)}catch(e){if(mounted.current)setError(e instanceof ApiError?e:new ApiError(0,"批次状态刷新失败"))}};const timer=window.setInterval(()=>void poll(),3000);return()=>window.clearInterval(timer)},[activeIds,locale]);
 const create=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setPending(x=>({...x,create:"创建中…"}));setNotice(null);const data=new FormData(event.currentTarget);try{await (await api()).createDiscoveryTopic({name:data.get("name"),description:data.get("description")||null,status:"paused",default_schedule:data.get("schedule"),default_max_videos:Number(data.get("max_videos")),default_max_pages:Number(data.get("max_pages")),default_max_comments_per_video:Number(data.get("max_comments")),queries:queries.filter(Boolean).map(query_text=>({query_text}))});setNotice(locale==="zh-CN"?"主题已创建。":"Topic created.");setQueries([""]);event.currentTarget.reset();await load()}catch(e){setError(e instanceof ApiError?new ApiError(e.status,locale==="zh-CN"?`创建失败：${e.message}`:`Create failed: ${e.message}`,e.code,e.requestId):new ApiError(0,"创建失败"))}finally{setPending(x=>{const y={...x};delete y.create;return y})}};
 const action=async(topic:DiscoveryTopic,kind:"run"|"toggle"|"duplicate")=>{const key=`${topic.id}:${kind}`;setPending(x=>({...x,[key]:kind==="run"?(locale==="zh-CN"?"排队中…":"Queuing…"):"处理中…"}));setNotice(null);try{const client=await api();if(kind==="run"){const batch=await client.runDiscoveryTopic(topic.id);setBatches(current=>({...current,[topic.id]:batch}));setNotice(locale==="zh-CN"?`发现批次已排队（${batch.queued_query_count}/${batch.requested_query_count}）。`:"Discovery batch queued.")}else if(kind==="duplicate"){await client.duplicateDiscoveryTopic(topic.id);setNotice(locale==="zh-CN"?"主题已复制。":"Topic duplicated.");await load()}else if(topic.status==="active"){await client.pauseDiscoveryTopic(topic.id);setNotice(locale==="zh-CN"?"主题已暂停。":"Topic paused.");await load()}else{await client.resumeDiscoveryTopic(topic.id);setNotice(locale==="zh-CN"?"主题已恢复。":"Topic resumed.");await load()}}catch(e){if(e instanceof ApiError&&e.status===409){setNotice(locale==="zh-CN"?"该主题已有批次在队列中或正在运行。":"This topic already has an active batch.");await load()}else{const verb=kind==="run"?"运行失败":kind==="duplicate"?"复制失败":topic.status==="active"?"暂停失败":"恢复失败";setError(e instanceof ApiError?new ApiError(e.status,`${verb}：${e.message}`,e.code,e.requestId):new ApiError(0,verb))}}finally{setPending(x=>{const y={...x};delete y[key];return y})}};
 return <div className="space-y-6"><PageHeader title={locale==="zh-CN"?"数据发现":"Discovery Operations"} description={locale==="zh-CN"?"配置、运行和监控受限的 YouTube 发现主题。":"Configure, run, and monitor bounded YouTube discovery topics."}/>{notice&&<p role="status" className="rounded-md border border-blue-200 bg-blue-50 px-4 py-3 text-sm text-blue-800">{notice}</p>}{system&&<section aria-label="系统状态" className="grid grid-cols-2 gap-2 md:grid-cols-5">{Object.entries(system).map(([key,value])=><div key={key} className="rounded-lg border bg-white p-3 dark:bg-slate-950"><p className="text-xs text-slate-500">{key}</p><p className="mt-1 font-medium">{value}</p></div>)}</section>}<CreateForm locale={locale} queries={queries} setQueries={setQueries} pending={pending.create} onSubmit={create}/>{loading?<div aria-label="正在加载数据发现" className="h-52 animate-pulse rounded-xl bg-slate-100"/>:error?<ErrorState message={error.message} requestId={error.requestId??undefined} onRetry={()=>void load(true)}/>:topics.length===0?<EmptyState title="暂无发现主题" description="创建一个手动主题以开始受控发现。"/>:<TopicTable topics={topics} batches={batches} pending={pending} action={action}/>}</div>
}

function CreateForm({locale,queries,setQueries,pending,onSubmit}:{locale:string;queries:string[];setQueries:React.Dispatch<React.SetStateAction<string[]>>;pending?:string;onSubmit:(e:FormEvent<HTMLFormElement>)=>void}){return <form onSubmit={onSubmit} aria-label="创建发现主题" className="rounded-xl border bg-white p-4 dark:bg-slate-950"><h2 className="font-semibold">{locale==="zh-CN"?"新建主题":"New topic"}</h2><div className="mt-3 grid gap-3 md:grid-cols-3"><Input name="name" label="Topic name" required/><Input name="description" label="Description"/><label><span className="text-xs text-slate-500">Schedule</span><select name="schedule" className="mt-1 h-10 w-full rounded-md border bg-transparent px-3"><option value="manual">Manual only</option><option value="6h">Every 6 hours</option><option value="12h">Every 12 hours</option><option value="daily">Daily</option><option value="weekly">Weekly</option></select></label><Input name="max_videos" label="Max videos" type="number" value="5"/><Input name="max_pages" label="Max pages" type="number" value="1"/><Input name="max_comments" label="Max comments/video" type="number" value="10"/></div><div className="mt-3 space-y-2"><p className="text-xs text-slate-500">YouTube queries</p>{queries.map((query,index)=><input key={index} aria-label={`Query ${index+1}`} value={query} onChange={e=>setQueries(current=>current.map((x,i)=>i===index?e.target.value:x))} className="h-10 w-full rounded-md border bg-transparent px-3"/>)}<button type="button" onClick={()=>setQueries(x=>[...x,""])} className={button}>+ Add query</button></div><button disabled={Boolean(pending)} className={`${button} mt-4 bg-slate-950 text-white dark:bg-white dark:text-slate-950`}>{pending??"Create topic"}</button></form>}
function TopicTable({topics,batches,pending,action}:{topics:DiscoveryTopic[];batches:Record<string,DiscoveryTopicRun>;pending:Record<string,string>;action:(topic:DiscoveryTopic,kind:"run"|"toggle"|"duplicate")=>Promise<void>}){return <div className="overflow-hidden rounded-xl border bg-white dark:bg-slate-950"><table className="w-full text-left text-sm"><thead className="border-b bg-slate-50 text-xs dark:bg-slate-900"><tr>{["Topic","Status","Queries","Schedule","Current batch","Result / quota","Actions"].map(x=><th key={x} className="px-3 py-3">{x}</th>)}</tr></thead><tbody className="divide-y">{topics.map(topic=>{const batch=batches[topic.id];const isActive=active(batch);const runPending=pending[`${topic.id}:run`];const m=batch?.intelligence_metrics??{};return <tr key={topic.id}><td className="px-3 py-4"><strong>{topic.name}</strong><p className="text-xs text-slate-500">{topic.description}</p></td><td className="px-3">{topic.status}</td><td className="px-3">{topic.query_count}</td><td className="px-3">{topic.default_schedule}</td><td className="px-3 text-xs">{batch?<div><p>{locale==="zh-CN"?"发现":"Discovery"}: {batch.status} · {batch.terminal_count}/{batch.requested_query_count}</p><p>{locale==="zh-CN"?"情报处理":"Intelligence"}: {batch.intelligence_status}</p><p className="text-slate-500">{m.discovery_results??0} results · {m.unique_videos??0} unique · {m.metadata_completed??0} metadata · {m.relevant_videos??0} relevant · {m.signals_created??0} signals · {m.opportunity_candidates_created??0} candidates</p>{batch.intelligence_error_summary?<p className="text-red-600">{batch.intelligence_error_summary}</p>:null}{batch.runs?.map(run=><p key={run.id} className={run.status==="failed"?"text-red-600":"text-slate-500"}>{run.query_text??run.query_id}: {run.status}{run.error_message_safe?` — ${run.error_message_safe}`:""}</p>)}</div>:"Idle"}</td><td className="px-3 text-xs">{batch?.status??topic.latest_run?.status??"—"} · quota {batch?.quota_estimate??topic.latest_run?.quota_estimate??"—"}</td><td className="px-3"><div className="flex flex-wrap gap-1"><button disabled={Boolean(runPending)||isActive||topic.status==="archived"} onClick={()=>void action(topic,"run")} className={button}>{runPending??(isActive?"Processing…":"Run Now")}</button><button disabled={Boolean(pending[`${topic.id}:toggle`])||topic.status==="archived"} onClick={()=>void action(topic,"toggle")} className={button}>{pending[`${topic.id}:toggle`]??(topic.status==="active"?"Pause":"Resume")}</button><button disabled={Boolean(pending[`${topic.id}:duplicate`])} onClick={()=>void action(topic,"duplicate")} className={button}>{pending[`${topic.id}:duplicate`]??"Duplicate"}</button></div></td></tr>})}</tbody></table></div>}
function Input({name,label,type="text",value,required=false}:{name:string;label:string;type?:string;value?:string;required?:boolean}){return <label><span className="text-xs text-slate-500">{label}</span><input name={name} type={type} defaultValue={value} required={required} min={type==="number"?0:undefined} className="mt-1 h-10 w-full rounded-md border bg-transparent px-3"/></label>}
