"use client";

import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { FormEvent, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ApiClient, ApiError } from "@/lib/api/client";
import { createClient } from "@/lib/auth/client";
import { useI18n } from "@/lib/i18n/context";
import type { ActivationReadiness, CandidateDetail, CandidatePage, CandidateSummary, CurrentUser, EvidencePage } from "@/lib/api/types";
import { SourceTrace } from "@/components/evidence/source-trace";

const box="rounded-xl border bg-white p-5 dark:bg-slate-950";
const button="rounded-md border px-4 py-2 text-sm disabled:opacity-40";
const input="mt-1 w-full rounded-md border bg-transparent p-2 text-sm";
const labels:Record<string,[string,string]>={
  emerging:["萌芽期","Emerging"],accelerating:["加速期","Accelerating"],validated:["已验证阶段","Validated"],crowded:["拥挤市场","Crowded"],mature:["成熟期","Mature"],declining:["衰退期","Declining"],low:["低","Low"],medium:["中","Medium"],high:["高","High"],
  resolved:["已处理","Resolved"],approve:["发布","Publish"],reject:["无效","Invalid"],defer:["暂缓","Defer"],
  ready:["可送审","Ready"],needs_review:["需人工判断","Needs review"],not_ready:["存在发布阻碍","Not ready"],
  none:["尚未提交发布审核","Not submitted"],pending:["待处理","Pending"],in_review:["审核中","In review"],deferred:["已暂缓","Deferred"],
  candidate:["候选","Candidate"],active:["已发布","Published"],rejected:["已标记无效","Invalid"],archived:["已归档","Archived"],
  pass:["通过","Pass"],warning:["注意","Warning"],fail:["未通过","Fail"],stale:["可能过期","Stale"],
  submitted:["已送审","Submitted"],claimed:["已领取","Claimed"],published:["已发布","Published"],invalid:["无效","Invalid"],
  supporting_evidence:["支持证据","Supporting evidence"],scope_clear:["范围清晰","Scope clarity"],commercial_definition:["商业定义","Commercial definition"],duplicate_risk:["重复风险","Duplicate risk"],source_diversity:["来源多样性","Source diversity"],contradiction_quality:["矛盾与质量","Contradiction and quality"],
  name:["名称","Name"],one_line_thesis:["一句话论点","One-line thesis"],problem:["问题","Problem"],solution:["解决方案","Solution"],business_model:["商业模式","Business model"],typical_price_min:["最低价格","Minimum price"],typical_price_max:["最高价格","Maximum price"],typical_price_currency:["币种（如 USD）","Currency (e.g. USD)"],typical_price_period:["计价周期","Price period"],market_stage:["市场阶段","Market stage"],competition_level:["竞争程度","Competition"],build_difficulty:["实现难度","Build difficulty"],
};
function useWords(){const {locale,enumLabel}=useI18n();const zh=locale==="zh-CN";return {locale,word:(a:string,b:string)=>zh?a:b,label:(key:string)=>labels[key]?.[zh?0:1]??enumLabel(key)}}
function useClient(){return useMemo(()=>new ApiClient(async()=>{const s=createClient();return s?(await s.auth.getSession()).data.session?.access_token??null:null}),[])}
function display(v:unknown){return v==null||v===""?"—":typeof v==="object"?JSON.stringify(v):String(v)}
function Stamp({value}:{value:string|null}){const {locale}=useWords();return <>{value?new Date(value).toLocaleString(locale):"—"}</>}
export function ReviewNavigation(){const {word}=useWords();return <nav aria-label={word("审核工作区","Review workspace")} className="flex gap-4 border-b pb-3 text-sm"><Link href="/admin/review" className="underline">{word("审核队列","Review queue")}</Link><Link href="/admin/review/candidates" className="underline">{word("候选机会","Candidate opportunities")}</Link></nav>}
function Failure({error,retry}:{error:unknown;retry:()=>void}){const {word}=useWords();return <div role="alert" className={box}><p>{error instanceof ApiError&&error.status===409?word("记录已变更或不满足操作条件，请刷新后检查。","The record changed or cannot accept this action. Reload and inspect."):word("请求未完成，请重试。","Request could not complete. Please retry.")}</p>{error instanceof ApiError&&error.requestId&&<p className="text-xs">{error.requestId}</p>}<button className={button} onClick={retry}>{word("重试","Retry")}</button>{error instanceof ApiError&&error.status!==0&&<p className="mt-2 text-sm">{display(error.message)}</p>}</div>}

export function CandidateList(){
  const api=useClient();const {word,label,locale}=useWords();const router=useRouter();const search=useSearchParams().toString();
  const [data,setData]=useState<CandidatePage|null>(null),[error,setError]=useState<unknown>(null),[loading,setLoading]=useState(true),[retry,setRetry]=useState(0);
  const [taxonomy,setTaxonomy]=useState<{industry:Array<{code:string;label:string}>;customer:Array<{code:string;label:string}>}>({industry:[],customer:[]});
  useEffect(()=>{let alive=true;void Promise.resolve().then(()=>{if(!alive)return;setLoading(true);setError(null);const query=Object.fromEntries(new URLSearchParams(search));(async()=>{const result=await api.listCandidates({...query,locale});const industry=await api.listTaxonomy("industry",locale);const customer=await api.listTaxonomy("customer",locale);return [result,industry,customer] as const})().then(([result,industry,customer])=>{if(alive){setData(result);setTaxonomy({industry,customer})}}).catch(e=>{if(alive)setError(e)}).finally(()=>{if(alive)setLoading(false)});});return()=>{alive=false}},[api,search,locale,retry]);
  function navigate(changes:Record<string,string>){const p=new URLSearchParams(search);Object.entries(changes).forEach(([k,v])=>v?p.set(k,v):p.delete(k));router.push(`/admin/review/candidates?${p}`)}
  function filter(e:FormEvent<HTMLFormElement>){e.preventDefault();navigate({...Object.fromEntries(new FormData(e.currentTarget)) as Record<string,string>,offset:"0"})}
  const params=new URLSearchParams(search);
  return <div className="space-y-5"><ReviewNavigation/><header><h1 className="text-2xl font-semibold">{word("候选机会","Candidate opportunities")}</h1><p className="mt-2 text-sm text-slate-500">{word("完善商业定义，核验证据，再提交人工发布审核。候选不代表已获认可。","Clarify the business definition, inspect evidence, then submit for human publication review. Candidates are not endorsements.")}</p></header>
    {data&&<div className="grid grid-cols-2 gap-3 lg:grid-cols-6">{[["total",word("候选总数","Total candidates")],["ready",label("ready")],["needs_review",label("needs_review")],["not_ready",label("not_ready")],["under_review",word("已送审","Open activation review")],["deferred",label("deferred")]].map(([k,title])=><div key={k} className={box}><p className="text-xs text-slate-500">{title}</p><strong className="text-2xl">{data.counts[k]}</strong></div>)}</div>}
    <form key={search+locale} onSubmit={filter} className={`${box} grid gap-3 md:grid-cols-4`}><label>{word("搜索","Search")}<input className={input} name="q" defaultValue={params.get("q")??""}/></label>{(["industry","customer"] as const).map(kind=><label key={kind}>{kind==="industry"?word("行业","Industry"):word("客户","Customer")}<select className={input} name={`${kind}_code`} defaultValue={params.get(`${kind}_code`)??""}><option value="">{word("全部","All")}</option>{taxonomy[kind].map(n=><option key={n.code} value={n.code}>{n.label}</option>)}</select></label>)}{[["readiness",word("就绪度","Readiness"),["ready","needs_review","not_ready"]],["review_state",word("发布审核","Activation review"),["none","pending","in_review","deferred"]]].map(([key,title,options])=><label key={key as string}>{title as string}<select className={input} name={key as string} defaultValue={params.get(key as string)??""}><option value="">{word("全部","All")}</option>{(options as string[]).map(v=><option key={v} value={v}>{label(v)}</option>)}</select></label>)}<label>{word("语义警告","Semantic warnings")}<select name="has_semantic_warnings" className={input} defaultValue={params.get("has_semantic_warnings")??""}><option value="">{word("全部","All")}</option><option value="true">{word("有","Yes")}</option><option value="false">{word("无","No")}</option></select></label><label>{word("排序","Sort")}<select name="sort" className={input} defaultValue={params.get("sort")??"priority"}>{[["priority",word("就绪度 → 证据 → 最近活动","Readiness → evidence → recent")],["recent",word("最近活动","Recent activity")],["name",word("名称","Name")]].map(([k,t])=><option key={k} value={k}>{t}</option>)}</select></label><button className={button}>{word("应用筛选","Apply filters")}</button></form>
    {loading?<p role="status">{word("正在加载候选机会…","Loading candidates…")}</p>:error?<Failure error={error} retry={()=>setRetry(r=>r+1)}/>:data?.items.length?<div className="space-y-3">{data.items.map(i=><article key={i.id} className={box}><div className="flex flex-wrap justify-between gap-2"><Link className="text-lg font-semibold underline" href={`/admin/review/candidates/${i.id}`}>{i.name}</Link><span>{label(i.readiness.overall)} · {label(i.review_state)}</span></div><p className="my-2 text-sm">{i.one_line_thesis||word("缺失：一句话论点","Missing: one-line thesis")}</p><p className="text-sm text-slate-500">{i.industry_taxonomy?.label??i.industry??word("行业待确认","Industry unknown")} · {i.customer_taxonomy?.label??i.customer_type??word("客户待确认","Customer unknown")}</p><Metrics summary={i}/></article>)}</div>:<p className={box}>{data?.counts.total?word("没有符合当前条件的候选机会","No candidates match these filters"):word("暂无候选机会","No candidate opportunities")}</p>}
    {data&&!loading&&!error&&<nav className="flex justify-between"><span>{word("筛选结果","Results")}: {data.total}</span><div className="flex gap-2"><button className={button} disabled={!data.offset} onClick={()=>navigate({offset:String(Math.max(0,data.offset-data.limit))})}>{word("上一页","Previous")}</button><button className={button} disabled={!data.has_more} onClick={()=>navigate({offset:String(data.offset+data.limit)})}>{word("下一页","Next")}</button></div></nav>}
  </div>
}
function Metrics({summary:s}:{summary:CandidateSummary}){const {word,label}=useWords();const e=s.evidence_summary,m=s.readiness.metrics;return <div className="mt-3 space-y-2 text-sm"><p>{word("有效关联 / 支持","Effective linked / supporting")}: {e.active_signal_count} / {e.supporting_signal_count} · {e.distinct_video_count} {word("视频","videos")} / {e.distinct_channel_count} {word("频道","channels")} · {word("语义警告","Semantic warnings")}: {s.semantic_warning_count}</p><p>{word("评分 / 置信度 / 炒作风险","Score / confidence / hype")}: {display(m.latest_score)} / {display(m.confidence_score)} / {display(m.hype_risk)}</p><p className="text-xs text-slate-500">{word("评分","Score")}: <Stamp value={s.score_at}/> ({s.score_freshness==="ready"?word("已更新","Ready"):label(s.score_freshness)}) · {word("趋势","Trend")}: <Stamp value={s.trend_at}/> ({s.trend_freshness==="ready"?word("已更新","Ready"):label(s.trend_freshness)}) · {word("最近活动","Last activity")}: <Stamp value={s.last_activity_at}/></p></div>}

export function CandidateDossier({id}:{id:string}){
  const api=useClient();const {word,label,locale}=useWords();const [data,setData]=useState<CandidateDetail|null>(null),[evidence,setEvidence]=useState<EvidencePage|null>(null),[user,setUser]=useState<CurrentUser|null>(null);
  const [error,setError]=useState<unknown>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[retry,setRetry]=useState(0),[excluded,setExcluded]=useState(false),[offset,setOffset]=useState(0),[notice,setNotice]=useState("");
  const [notes,setNotes]=useState(""),[confirmation,setConfirmation]=useState<"approve"|"reject"|null>(null),[visible,setVisible]=useState<boolean|null>(null);
  const inFlight=useRef(false);
  const load=useCallback(async()=>{const d=await api.getCandidate(id,{locale});setData(d);return d},[api,id,locale]);
  useEffect(()=>{let alive=true;void Promise.resolve().then(()=>{if(!alive)return;setLoading(true);setError(null);setEvidence(null);(async()=>{const d=await api.getCandidate(id,{locale});const e=await api.getCandidateEvidence(id,{locale,excluded,offset,limit:20});const u=await api.getCurrentUser();return [d,e,u] as const})().then(async([d,e,u])=>{if(!alive)return;setData(d);setEvidence(e);setUser(u);if(d.opportunity.status==="active"){try{await api.getOpportunity(id);if(alive)setVisible(true)}catch{if(alive)setVisible(false)}}}).catch(e=>{if(alive)setError(e)}).finally(()=>{if(alive)setLoading(false)});});return()=>{alive=false}},[api,id,locale,excluded,offset,retry]);
  async function action(work:()=>Promise<unknown>,message:string){if(inFlight.current)return;inFlight.current=true;setBusy(true);setError(null);try{await work();setNotice(message);await load();setRetry(r=>r+1)}catch(e){setError(e)}finally{inFlight.current=false;setBusy(false);setConfirmation(null)}}
  function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!data)return;const form=Object.fromEntries(new FormData(e.currentTarget));const body:Record<string,unknown>={expected_updated_at:data.opportunity.updated_at,note:form.edit_note||null};for(const [key,value]of Object.entries(form)){if(key==="edit_note")continue;const before=data.opportunity[key as keyof typeof data.opportunity];if(String(before??"")!==value)body[key]=value||null}void action(()=>api.editCandidate(id,body),word("草稿已保存；未发布。","Draft saved; publication is unchanged."))}
  async function decide(decision:"approve"|"reject"|"defer"){const review=data?.summary.activation_review;if(!review)return;await action(()=>api.decideReview(review.id,{decision,decision_notes:notes||null}),decision==="approve"?word("已发布，正在核验前台可见性。","Published; checking product visibility."):decision==="defer"?word("已暂缓，候选保持非公开。","Deferred; candidate remains non-public."):word("已标记无效，历史保留。","Marked invalid; history retained."))}
  if(loading&&!data)return <p role="status">{word("正在加载候选详情…","Loading candidate…")}</p>;
  if(!data)return <Failure error={error} retry={()=>setRetry(r=>r+1)}/>;
  const o=data.opportunity,s=data.summary,review=s.activation_review,canDecide=review?.status==="in_review"&&review.assigned_to===user?.user_profile_id;
  const textFields=["name","one_line_thesis","problem","solution","business_model","typical_price_min","typical_price_max","typical_price_currency","typical_price_period"] as const;
  return <div className="space-y-5"><ReviewNavigation/><header><p className="text-sm text-slate-500">{label(o.status)}</p><h1 className="text-2xl font-semibold">{o.name}</h1><p className="mt-2">{o.one_line_thesis||word("缺失：一句话论点","Missing: one-line thesis")}</p><p className="mt-2 text-sm">{s.industry_taxonomy?.label??o.industry??word("行业待确认","Industry unknown")} · {s.customer_taxonomy?.label??o.customer_type??word("客户待确认","Customer unknown")}</p><Metrics summary={s}/></header>
    {notice&&<p role="status" className="rounded border border-emerald-300 p-3">{notice}</p>}{Boolean(error)&&<Failure error={error} retry={()=>setRetry(r=>r+1)}/>}
    {o.status==="active"&&<section className={box}><h2 className="font-semibold">{word("已发布","Published")}</h2><p>{visible?word("前台读取已确认可见。","Visibility confirmed through the product API."):word("前台可见性待确认，请刷新。","Product visibility is pending verification. Refresh to retry.")}</p><Link className="underline" href={`/opportunities/${id}`}>{word("查看前台机会","View published opportunity")}</Link><p className="mt-2 text-sm">{word("评分","Score")}: {s.score_freshness==="ready"?word("已更新","Ready"):label(s.score_freshness)} · {word("翻译","Translation")}: {data.translation_state==="ready"?word("已有当前翻译","Current translation available"):word("待处理或待更新","Pending or stale")}</p><p className="text-xs text-slate-500">{word("发布不保证即时雷达排名；排名还取决于评分、筛选和后续计算。","Publication does not guarantee immediate Radar ranking; scores, filters and downstream processing still apply.")}</p></section>}
    {o.status==="candidate"?<ReadinessPanel readiness={s.readiness}/>:<p className={box}>{word("当前记录不再处于候选状态，发布就绪度不适用；以下资料仅供查看。","This record is no longer a candidate. Activation readiness is not applicable; the dossier below is read-only.")}</p>}
    <section className={box}><h2 className="font-semibold">{word("商业定义","Business definition")}</h2><form key={o.updated_at} onSubmit={save} className="mt-3 grid gap-4 sm:grid-cols-2">{textFields.map(k=><label key={k}>{label(k)}{!o[k]&&<span className="ml-2 text-xs text-amber-700">{word("缺失","Missing")}</span>}{["problem","solution","one_line_thesis"].includes(k)?<textarea className={input} rows={3} name={k} defaultValue={o[k]??""} disabled={o.status!=="candidate"||busy}/>:<input className={input} name={k} required={k==="name"} type={k.startsWith("typical_price_m")?"number":"text"} min={k.startsWith("typical_price_m")?0:undefined} step={k.startsWith("typical_price_m")?"any":undefined} defaultValue={o[k]??""} disabled={o.status!=="candidate"||busy}/>}</label>)}{(["market_stage","competition_level","build_difficulty"] as const).map(k=><label key={k}>{label(k)}<select name={k} className={input} defaultValue={o[k]??""} disabled={o.status!=="candidate"||busy}>{k!=="market_stage"&&<option value="">{word("待确认","Unknown")}</option>}{(k==="market_stage"?["unknown","emerging","accelerating","validated","crowded","mature","declining"]:["unknown","low","medium","high"]).map(v=><option key={v} value={v}>{label(v)}</option>)}</select></label>)}<p className="text-sm sm:col-span-2">{word("分销：当前没有独立的可编辑字段，请检查下方 distribution 证据。分类映射在此仅供查看。","Distribution has no separate editable field; inspect distribution evidence below. Taxonomy mappings are read-only here.")}</p>{o.status==="candidate"&&<><label className="sm:col-span-2">{word("编辑说明","Edit note")}<textarea className={input} name="edit_note" maxLength={2000}/></label><button disabled={busy} className={button}>{word("保存草稿","Save draft")}</button></>}</form></section>
    <section className={box}><h2 className="font-semibold">{word("证据与来源","Evidence and sources")}</h2><div className="my-3 flex gap-3"><button className={button} aria-pressed={!excluded} onClick={()=>{setExcluded(false);setOffset(0)}}>{word("有效证据","Effective evidence")}</button><button className={button} aria-pressed={excluded} onClick={()=>{setExcluded(true);setOffset(0)}}>{word("排除与待审核证据","Excluded and under-review evidence")}</button></div>{excluded&&<p className="mb-3 text-sm text-amber-700">{word("这些证据保留供核验，不计入有效支持或发布就绪度。","Retained for inspection; these records do not count as effective support or readiness.")}</p>}{loading?<p role="status">{word("加载中…","Loading…")}</p>:evidence?.items.length?<div className="space-y-3">{evidence.items.map(e=><article key={e.evidence_id} className="space-y-2 rounded-lg border p-4"><p className="text-xs text-slate-500">{label(e.signal_type??e.evidence_type)} · {label(e.relationship_type??"unknown")} · {label(e.claim_status??"unknown")} · {label(e.semantic_status??"current")} · {word("记录状态","Record status")}: {e.signal_status??"—"}</p><h3 className="font-medium">{e.statement}</h3><p className="text-sm">{e.evidence_text}</p>{(e.statement_localized||e.evidence_localized)&&<details><summary>{word("查看原始提取文本","Canonical extracted text")}</summary><p>{e.original_statement}</p><p>{e.original_evidence_text}</p></details>}<SourceTrace source={e}/></article>)}</div>:<p>{error?word("证据加载未完成，请重试。","Evidence could not load. Please retry."):excluded?word("没有被排除的证据","No excluded evidence"):word("证据不足","Insufficient evidence")}</p>}<div className="mt-3 flex items-center justify-between"><span>{word("证据总数","Evidence total")}: {evidence?.total??"—"}</span><div className="flex gap-2"><button className={button} disabled={!offset||loading} onClick={()=>setOffset(Math.max(0,offset-20))}>{word("上一页","Previous")}</button><button className={button} disabled={!evidence?.has_more||loading} onClick={()=>setOffset(offset+20)}>{word("下一页","Next")}</button></div></div></section>
    <section className={box}><h2 className="font-semibold">{word("发布审核","Activation review")}</h2>{review?<><p className="my-2">{label(s.review_state)} · {review.assigned_to===user?.user_profile_id?word("由我审核","Assigned to me"):review.assigned_to?word("其他管理员审核中","Assigned to another admin"):word("尚未领取","Unassigned")} · <Stamp value={review.created_at}/></p><Link className="underline" href={`/admin/review?selected=${review.id}&status=${review.status}`}>{word("查看发布审核","View activation review")}</Link>{review.decision_notes&&<p className="mt-2">{review.decision_notes}</p>}{o.status==="candidate"&&<div className="mt-3 space-y-3"><label className="block">{word("审核理由","Review notes")}<textarea className={input} value={notes} onChange={e=>setNotes(e.target.value)} maxLength={2000}/></label>{review.status==="pending"?<button className={button} disabled={busy} onClick={()=>void action(()=>api.claimReview(review.id),word("已领取发布审核","Activation review claimed"))}>{word("领取审核","Claim review")}</button>:<div className="flex gap-2"><button className={button} disabled={busy||!canDecide||s.readiness.overall==="not_ready"} onClick={()=>setConfirmation("approve")}>{word("发布","Publish")}</button><button className={button} disabled={busy||!canDecide} onClick={()=>void decide("defer")}>{word("暂缓","Defer")}</button><button className={button} disabled={busy||!canDecide} onClick={()=>setConfirmation("reject")}>{word("标记无效","Invalid")}</button></div>}</div>}</>:o.status==="candidate"?<><p className="my-2">{word("尚未提交发布审核","No activation review submitted")}</p><p className="mb-3 text-sm text-slate-500">{word("至少需要一条有效支持证据才能送审。其他阻碍可在审核中处理，但发布时必须通过。","Submission requires at least one effective supporting signal. Other blockers may be reviewed but must pass before publication.")}</p><button className={button} disabled={busy||s.readiness.metrics.active_signal_count<1} onClick={()=>void action(()=>api.submitCandidate(id),word("已创建或复用发布审核","Activation review created or reused"))}>{word("提交发布审核","Submit for activation review")}</button></>:<p>{label(o.status)}</p>}</section>
    <section className={box}><h2 className="font-semibold">{word("编辑与审核历史","Edit and review history")}</h2><ul className="mt-3 space-y-3">{data.revisions.map(r=><li key={r.id} className="border-b pb-2 text-sm"><Stamp value={r.changed_at}/> · {label(r.field)}: {display(r.old_value)} → {display(r.new_value)}<p>{r.note}</p><details><summary>{word("操作人","Actor")}</summary>{r.changed_by}</details></li>)}{data.review_history.map(e=><li key={e.id} className="border-b pb-2 text-sm"><Stamp value={e.created_at}/> · {label(e.event_type)} · {label(e.status)}<p>{e.notes}</p><details><summary>{word("操作人","Actor")}</summary>{e.actor_id??word("未记录","Not recorded")}</details></li>)}</ul>{!data.revisions.length&&!data.review_history.length&&<p>{word("暂无新增事件","No new events recorded")}</p>}{data.legacy_reviews.length>0&&<details className="mt-3"><summary>{word("审核任务状态快照（不推测历史事件）","Review task snapshots (no inferred historical events)")}</summary>{data.legacy_reviews.map(r=><p key={r.id} className="mt-2 text-sm"><Stamp value={r.updated_at}/> · {label(r.status)} · {r.decision?label(r.decision):"—"} · {r.decision_notes}</p>)}</details>}{data.history_has_more&&<p>{word("仅显示最近 100 条记录；更早历史仍保留。","Showing the latest 100 records; older history remains retained.")}</p>}</section>
    {confirmation&&<div role="dialog" aria-modal="true" aria-label={word("确认审核决定","Confirm review decision")} className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><div className={`${box} max-w-lg space-y-4`}><h2>{confirmation==="approve"?word("确认发布此候选？","Publish this candidate?"):word("确认标记为无效？","Mark this candidate invalid?")}</h2><p>{confirmation==="approve"?word("发布后普通用户可以查看；这不代表商业结论已被证实。","Publication makes this visible to product users; it does not verify commercial claims."):word("候选将保持非公开，证据与历史会保留。","The candidate remains non-public; evidence and history are retained.")}</p><button className={button} disabled={busy} onClick={()=>setConfirmation(null)}>{word("取消","Cancel")}</button><button className={button} disabled={busy} onClick={()=>void decide(confirmation)}>{word("确认决定","Confirm decision")}</button></div></div>}
  </div>
}

function ReadinessPanel({readiness:r}:{readiness:ActivationReadiness}){const {word,label}=useWords();const actions:Record<string,string>={supporting_evidence:word("核验并补充有效支持信号。","Verify and add effective supporting signals."),scope_clear:word("将名称和描述限定为明确的商业场景。","Make the name and description specific to a business use case."),commercial_definition:word("补充客户、问题和解决方案中的缺失项。","Complete missing customer, problem and solution definitions."),duplicate_risk:word("打开相似机会比较；不要重复发布。","Inspect suggested opportunities before publishing a duplicate."),source_diversity:word("寻找更多视频或频道的支持证据。","Seek supporting evidence from additional videos or channels."),contradiction_quality:word("逐条检查待审核、矛盾和被排除的证据。","Inspect unresolved, contradicting and excluded evidence.")};return <section className={box}><h2 className="font-semibold">{word("发布就绪度","Activation readiness")}: {label(r.overall)}</h2><p className="my-2 text-sm text-slate-500">{word("评分与置信度仅供参考，不自动决定发布。","Scores and confidence are advisory and never publish automatically.")}</p><div className="grid gap-3 md:grid-cols-2">{Object.entries(r.checks).map(([key,c])=><article key={key} className="rounded border p-3"><h3 className="font-medium">{label(key)} · {label(c.status)}</h3><p className="mt-1 text-sm">{c.message}</p><dl className="my-2 text-xs">{Object.entries(c.supporting_metrics).map(([k,v])=><div key={k}><dt className="inline">{metricName(k,word)}: </dt><dd className="inline">{display(v)}</dd></div>)}</dl><p className="text-sm text-slate-500">{actions[key]}</p></article>)}</div><h3 className="mt-4 font-medium">{word("可能重复的机会","Possible duplicates")}</h3>{r.duplicate_candidates.length?<ul>{r.duplicate_candidates.map(d=><li key={d.opportunity_id} className="mt-2"><Link className="underline" href={d.status==="active"?`/opportunities/${d.opportunity_id}`:`/admin/review/candidates/${d.opportunity_id}`}>{d.name}</Link> · {label(d.status)} · {word("词汇重合","Lexical overlap")}: {d.overlap}</li>)}</ul>:<p className="text-sm text-slate-500">{word("未发现强词汇重复；这不保证语义上没有重复。","No strong lexical duplicate found; semantic duplicates may still exist.")}</p>}</section>}
function metricName(k:string,word:(a:string,b:string)=>string){const names:Record<string,[string,string]>={active_signal_count:["有效支持信号","Effective supporting signals"],name:["名称","Name"],populated_fields:["已填字段","Populated fields"],required:["要求字段数","Required fields"],candidate_count:["相似机会数","Similar opportunities"],distinct_video_count:["视频数","Videos"],distinct_channel_count:["频道数","Channels"],contradicting_active_signals:["有效矛盾证据","Effective contradictions"],unresolved_review_signals:["未完成审核信号","Unresolved signals"]};return names[k]?word(...names[k]):k}
