"use client";

import { FormEvent, useCallback, useEffect, useRef, useState } from "react";
import type { ApiClient } from "@/lib/api/client";
import type { EvidencePage } from "@/lib/api/types";
import { useI18n } from "@/lib/i18n/context";
import { SourceTrace } from "@/components/evidence/source-trace";

const dimensions = {
  customer_summary: ["客户与运营者", "Customer and operator"],
  problem_summary: ["客户问题", "Problem"], workflow_summary: ["业务流程", "Workflow"],
  solution_pattern: ["解决方案模式", "Solution pattern"], business_model_summary: ["商业模式", "Business model"],
  pricing_summary: ["定价证据", "Pricing evidence"], revenue_summary: ["收入证据", "Revenue evidence"],
  distribution_summary: ["分销与获客", "Distribution"], competition_summary: ["竞争与替代方案", "Competition"],
  adoption_summary: ["实际采用", "Adoption"], build_complexity_summary: ["技术与实现", "Build considerations"],
} as const;
type Dimension = keyof typeof dimensions;
type Field = {text:string|null;evidence_signal_ids:string[];information_class:string;support_level:string;uncertainty:string|null};
type Case = {id:string;version:number;status?:string;review_status?:string;created_at?:string;parsed_output:Record<Dimension,Field>&{validation_gaps:string[]};field_metadata:Record<Dimension,{video_count:number;channel_count:number;multi_video_coverage:boolean;claim_statuses:Record<string,number>}>};
export type BusinessCaseView = {state:string;case:Case|null;latest_attempt?:{id:string;status:string;error_code:string|null};opportunity_updated_at?:string;opportunity_status?:string;history?:Case[];history_has_more?:boolean};
const button = "rounded border px-3 py-2 text-sm disabled:opacity-40";
const editable:Dimension[]=["problem_summary","workflow_summary","solution_pattern","business_model_summary"];

export function BusinessCasePanel({id,api,admin=false,onAccepted}:{id:string;api:ApiClient;admin?:boolean;onAccepted?:()=>void}) {
  const {locale}=useI18n(); const zh=locale==="zh-CN";
  const word=(cn:string,en:string)=>zh?cn:en;
  const [data,setData]=useState<BusinessCaseView|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
  const [dimension,setDimension]=useState<Dimension|null>(null),[evidence,setEvidence]=useState<EvidencePage|null>(null),[offset,setOffset]=useState(0),[evidenceError,setEvidenceError]=useState(""),[evidenceRetry,setEvidenceRetry]=useState(0);
  const [proposal,setProposal]=useState<Dimension|null>(null),[confirm,setConfirm]=useState(false);
  const inFlight=useRef(false);
  const base=admin?`/api/v1/admin/opportunities/${id}/consolidation`:`/api/v1/opportunities/${id}/business-case`;
  const load=useCallback(async()=>{const result=await api.request<BusinessCaseView>(admin?`${base}/current`:base);setData(result);return result},[api,admin,base]);
  useEffect(()=>{let alive=true;void api.request<BusinessCaseView>(admin?`${base}/current`:base).then(r=>{if(alive)setData(r)}).catch(()=>{if(alive)setError("load")});return()=>{alive=false}},[api,admin,base]);
  useEffect(()=>{if(!admin||!["queued","running"].includes(data?.latest_attempt?.status??""))return;const timer=setInterval(()=>{void load().catch(()=>setError("load"))},4000);return()=>clearInterval(timer)},[admin,data?.latest_attempt?.status,load]);
  useEffect(()=>{let alive=true;void Promise.resolve().then(()=>{if(!alive)return;setEvidence(null);setEvidenceError("");if(dimension)void api.request<EvidencePage>(`${base}/evidence/${dimension}?locale=${locale}&offset=${offset}&limit=20`).then(r=>{if(alive)setEvidence(r)}).catch(()=>{if(alive)setEvidenceError("load")});});return()=>{alive=false}},[api,base,dimension,locale,offset,evidenceRetry]);
  async function act(work:()=>Promise<unknown>,message:string){if(inFlight.current)return;inFlight.current=true;setBusy(true);setError("");try{const result=await work() as {dispatch_failed?:boolean};setNotice(result?.dispatch_failed?word("请求已保存，但队列派发失败。请再次点击刷新重试。","Request saved; queue dispatch failed. Refresh again to retry."):message);setProposal(null);setConfirm(false);await load();onAccepted?.()}catch{setError("action")}finally{setBusy(false);inFlight.current=false}}
  function accept(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!data?.case||!proposal)return;const form=new FormData(event.currentTarget);void act(()=>api.request(`/api/v1/admin/opportunities/${id}/consolidations/${data.case!.id}/accept`,{method:"POST",body:JSON.stringify({dimension:proposal,expected_updated_at:data.opportunity_updated_at,edited_text:String(form.get("text")),note:String(form.get("note"))})}),word("字段已采纳并留痕。人工上下文已变化，请重新整理论证。","Field accepted with audit history. Human context changed; refresh the business case."))}
  const stateLabel:Record<string,string>={current:word("当前","Current"),stale:word("已过期","Stale"),missing:word("尚未整理","Missing"),unavailable:word("待验证／待审核","Awaiting evidence or review"),queued:word("已排队","Queued"),running:word("整理中","Running"),failed:word("失败，可重试","Failed; retry available"),completed:word("已完成","Completed")};
  const labels:Record<string,string>={source_grounded:word("来源陈述（保留原声明属性）","Source-grounded observation (claim status retained)"),editorial_synthesis:word("编辑综合判断","Editorial synthesis"),hypothesis:word("待验证假设","Hypothesis"),unknown:word("未知","Unknown"),supported:word("有证据支持","Supported"),partially_supported:word("部分支持","Partially supported"),insufficient_evidence:word("证据不足","Evidence insufficient")};
  const current=data?.state==="current"; const caseData=data?.case;
  return <section id="business-case" className="space-y-4 rounded-xl border p-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-semibold">{word("机会商业论证","Opportunity business case")}</h2>{admin&&<button className={button} disabled={busy||data?.latest_attempt?.status==="running"} onClick={()=>void act(()=>api.request(base,{method:"POST"}),word("整理请求已提交；完成后自动更新。","Refresh requested; results update when complete."))}>{word("重新整理机会论证","Refresh business case")}</button>}</div>
    <p>{word("状态","Status")}: {data?stateLabel[data.state]??data.state:word("加载中…","Loading…")}{data?.latest_attempt&&` · ${stateLabel[data.latest_attempt.status]??data.latest_attempt.status}`}</p>
    <p className="text-sm text-slate-500">{word("机器整理与人工定义分开保存。正文为英文原文；来源声明不等于已验证事实，多个视频不等于多个独立客户。","Machine synthesis is separate from human definitions. Canonical text is English. Source claims are not verified facts; multiple videos are not independent customers.")}</p>
    {admin&&!current&&<p className="text-amber-700">{word("发布前请检查：论证缺失或过期。该提示不替代现有发布审核。","Before publication: business case is missing or stale. This advisory does not replace activation review.")}</p>}
    {notice&&<p role="status">{notice}</p>}{error&&<p role="alert">{word("论证读取或操作未完成，请刷新核对状态。","Business-case request failed. Reload to check the recorded state.")} <button className={button} onClick={()=>void load().then(()=>setError("")).catch(()=>setError("load"))}>{word("重试读取","Retry read")}</button></p>}
    {caseData&&admin&&<p className="text-sm">v{caseData.version} · {caseData.review_status==="approved"?word("已人工确认","Human confirmed"):word("待人工确认，未公开展示","Awaiting human confirmation; not publicly displayed")}</p>}
    {caseData&&!current&&<p className="text-amber-700">{word("以下为历史版本，仅供比较，不能作为当前支持。","Historical version below is for comparison, not current support.")}</p>}
    <div className="grid gap-3 md:grid-cols-2">{(Object.keys(dimensions) as Dimension[]).map(key=>{const f=caseData?.parsed_output[key];return <article key={key} className="space-y-2 rounded border p-3"><h3 className="font-medium">{dimensions[key][zh?0:1]}</h3><p>{f?.text??word("证据不足／待验证","Evidence insufficient / to validate")}</p>{f&&<><p className="text-xs text-slate-500">{labels[f.information_class]} · {labels[f.support_level]}</p>{f.uncertainty&&<p className="text-sm text-amber-700">{f.uncertainty}</p>}{f.evidence_signal_ids.length>0&&<><p className="text-xs">{word("引用","References")}: {f.evidence_signal_ids.length} · {word("视频覆盖","Video coverage")}: {caseData?.field_metadata[key]?.video_count??0}</p><button className={button} disabled={!current} onClick={()=>{setDimension(key);setOffset(0);setEvidenceRetry(r=>r+1)}}>{word("查看证据","View evidence")} · {dimensions[key][zh?0:1]}</button></>}{admin&&current&&data?.opportunity_status==="candidate"&&editable.includes(key)&&["supported","partially_supported"].includes(f.support_level)&&<button className={`${button} ml-2`} disabled={busy} onClick={()=>setProposal(key)}>{word("采纳或编辑","Accept or edit")} · {dimensions[key][zh?0:1]}</button>}</>}</article>})}</div>
    <div><h3 className="font-semibold">{word("待验证问题","Validation gaps")}</h3>{caseData?<ul className="list-disc space-y-1 pl-5">{caseData.parsed_output.validation_gaps.map((gap,i)=><li key={i}>{gap}</li>)}</ul>:<p>{word("尚无当前且已审核的商业论证，请先核验现有证据。","No current reviewed business case yet. Inspect existing evidence first.")}</p>}</div>
    {admin&&current&&caseData&&caseData.review_status!=="approved"&&<button className={button} disabled={busy} onClick={()=>setConfirm(true)}>{word("确认此版论证可展示","Confirm case for display")}</button>}
    {dimension&&current&&<div className="space-y-3 rounded border p-4"><h3>{word("论证证据","Case evidence")} · {dimensions[dimension][zh?0:1]}</h3>{evidenceError?<p role="alert">{word("证据加载失败；请重新选择该维度重试。","Evidence failed to load; select the dimension again to retry.")}</p>:!evidence?<p role="status">{word("加载证据…","Loading evidence…")}</p>:<>{evidence.items.map(e=><article key={e.evidence_id} className="space-y-2 border-b py-3"><p>{e.statement}</p><p className="text-sm">{e.evidence_text}</p><p className="text-xs">{e.claim_status} · {e.relationship_type}</p><SourceTrace source={e}/></article>)}<p>{word("证据总数","Evidence total")}: {evidence.total}</p><button className={button} disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-20))}>{word("上一页","Previous")}</button><button className={button} disabled={!evidence.has_more} onClick={()=>setOffset(offset+20)}>{word("下一页","Next")}</button></>}<button className={button} onClick={()=>setDimension(null)}>{word("关闭证据","Close evidence")}</button></div>}
    {admin&&data?.history&&data.history.length>0&&<details><summary>{word("论证版本历史","Business-case history")}</summary>{data.history.map(row=><details id={`business-case-${row.id}`} key={row.id} className="my-2 border p-2"><summary>v{row.version} · {stateLabel[row.status??""]??row.status} · {row.created_at}</summary><p>{row.id}</p>{row.parsed_output&&<ul>{(Object.keys(dimensions) as Dimension[]).map(k=><li key={k}>{dimensions[k][zh?0:1]}: {row.parsed_output[k].text??word("证据不足","Evidence insufficient")}</li>)}</ul>}</details>)}</details>}
    {admin&&data?.history_has_more&&<p>{word("仅显示最近 100 个版本，更早记录仍保留。","Only the latest 100 versions are shown; older records remain stored.")}</p>}
    {proposal&&caseData&&<div role="dialog" aria-modal="true" aria-label={word("采纳论证字段","Accept case field")} className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><form onSubmit={accept} className="w-full max-w-xl space-y-4 rounded bg-white p-5 dark:bg-slate-950"><h3>{dimensions[proposal][zh?0:1]}</h3><label className="block">{word("采纳文本","Accepted text")}<textarea name="text" required maxLength={proposal==="business_model_summary"?300:3000} className="mt-2 w-full border bg-transparent p-2" rows={5} defaultValue={caseData.parsed_output[proposal].text??""}/></label><label className="block">{word("采纳说明","Acceptance note")}<textarea name="note" required maxLength={2000} className="mt-2 w-full border bg-transparent p-2"/></label><button type="button" className={button} onClick={()=>setProposal(null)}>{word("保留当前","Keep current")}</button><button className={button} disabled={busy}>{word("确认采纳字段","Confirm field acceptance")}</button></form></div>}
    {confirm&&caseData&&<div role="dialog" aria-modal="true" aria-label={word("确认论证展示","Confirm case display")} className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><div className="max-w-lg space-y-4 rounded bg-white p-5 dark:bg-slate-950"><p>{word("确认已核验证据、声明和缺口？只有已发布机会的当前已确认论证会向普通用户展示；本操作不会发布候选。","Have you checked evidence, claims and gaps? Only current confirmed cases of published opportunities are displayed to users. This does not publish a candidate.")}</p><button className={button} onClick={()=>setConfirm(false)}>{word("取消","Cancel")}</button><button className={button} disabled={busy} onClick={()=>void act(()=>api.request(`/api/v1/admin/opportunities/${id}/consolidations/${caseData.id}/approve`,{method:"POST"}),word("论证已确认；机会发布状态未改变。","Business case confirmed; opportunity publication state unchanged."))}>{word("确认展示","Confirm display")}</button></div></div>}
  </section>
}
