export type AppRole = "user" | "admin";
export interface CurrentUser { auth_user_id:string; user_profile_id:string; role:AppRole; email:string|null }
export type MarketStage = "unknown"|"emerging"|"accelerating"|"validated"|"crowded"|"mature"|"declining";
export interface TrendItem { window_type:string;period_start:string;period_end:string;aggregation_version:string;video_count:number;new_video_count:number;unique_channel_count:number;total_views:number;comment_count:number;pain_signal_count:number;demand_signal_count:number;purchase_intent_signal_count:number;revenue_signal_count:number;competitor_signal_count:number;momentum_score:string|null }
export interface EvidenceSummary { active_signal_count:number;supporting_signal_count?:number;distinct_video_count:number;distinct_channel_count:number;pain_signal_count:number;demand_signal_count:number;purchase_intent_signal_count:number;revenue_signal_count:number }
export interface TaxonomyProjection { code:string;label:string }
export interface RadarOpportunity { id:string;slug:string;name:string;one_line_thesis:string|null;industry:string|null;sub_industry:string|null;customer_type:string|null;industry_taxonomy?:TaxonomyProjection|null;customer_taxonomy?:TaxonomyProjection|null;business_model:string|null;market_stage:MarketStage;competition_level:string|null;build_difficulty:string|null;sales_difficulty:string|null;opportunity_score:string|null;confidence_score:string|null;hype_risk_score:string|null;trend:TrendItem|null;first_detected_at:string;last_activity_at:string;evidence_summary:EvidenceSummary;watchlisted:boolean }
export interface RadarResponse { items:RadarOpportunity[];total:number;offset:number;limit:number }
export interface OpportunityLibraryResponse { items:RadarOpportunity[];total:number;page:number;page_size:number;total_pages:number }
export interface DiscoveryRun {id:string;topic_id:string|null;topic_run_id:string|null;query_id:string|null;query_text:string|null;trigger_type:string;status:string;started_at:string|null;completed_at:string|null;videos_discovered:number;quota_estimate:number|null;error_code?:string|null;error_message_safe:string|null;worker_message_id:string|null}
export interface DiscoveryTopicRun {id:string;topic_id:string;trigger_type:string;status:"queued"|"running"|"completed"|"partial"|"failed";requested_query_count:number;queued_query_count:number;queued:number;running:number;completed:number;partial:number;failed:number;terminal_count:number;quota_estimate:number;started_at:string;completed_at:string|null;intelligence_status:"not_started"|"queued"|"processing"|"completed"|"partial"|"failed";intelligence_metrics:Record<string,number|boolean>;intelligence_error_summary:string|null;intelligence_started_at:string|null;intelligence_completed_at:string|null;runs?:DiscoveryRun[]}
export interface DiscoveryQueryConfig {id:string;topic_id:string;query_text:string;enabled:boolean;query_group:"discovery";discovery_mode:"discovery";max_videos:number|null;max_pages:number|null;max_comments_per_video:number|null;schedule_override:string|null;last_run_at:string|null}
export interface DiscoveryTopic {id:string;name:string;description:string|null;status:"active"|"paused"|"archived";default_schedule:string;default_max_videos:number;default_max_pages:number;default_max_comments_per_video:number;query_count:number;last_run_at:string|null;next_run_at:string|null;latest_run:DiscoveryRun|null;current_topic_run:DiscoveryTopicRun|null;queries?:DiscoveryQueryConfig[];recent_runs?:DiscoveryRun[]}
export interface DiscoverySystemStatus {redis:string;worker:string;scheduler:string;youtube_api:string;openai_api:string}
export interface DiscoveryRunPage {items:DiscoveryRun[];total:number;page:number;page_size:number}
export interface ScoreItem { calculated_at:string;scoring_version:string;trend_velocity_score:string;demand_evidence_score:string;revenue_evidence_score:string;pain_severity_score:string;competition_white_space_score:string;build_feasibility_score:string;distribution_ease_score:string;opportunity_score:string;confidence_score:string|null;hype_risk_score:string|null }
export interface OpportunityDetailData { id:string;slug:string;name:string;one_line_thesis:string|null;industry:string|null;sub_industry:string|null;customer_type:string|null;industry_taxonomy?:TaxonomyProjection|null;customer_taxonomy?:TaxonomyProjection|null;problem:string|null;solution:string|null;business_model:string|null;primary_technology:string|null;typical_price_min:string|null;typical_price_max:string|null;typical_price_currency:string|null;typical_price_period:string|null;competition_level:string|null;build_difficulty:string|null;sales_difficulty:string|null;market_stage:MarketStage;first_detected_at:string;last_activity_at:string }
export interface OpportunityDetail { opportunity:OpportunityDetailData;current_intelligence:ScoreItem|null;trend_summary:Record<"7d"|"30d"|"90d",TrendItem|null>;evidence_summary:EvidenceSummary;watchlisted:boolean }
export interface SourceProvenance { actor_role?:string;evidence_role?:string; source_video_id?:string|null;youtube_video_id?:string|null;video_title?:string|null;channel_name?:string|null;source_comment_id?:string|null;youtube_comment_id?:string|null;source_comment_text?:string|null;source_url?:string|null;source_navigation?:"video"|"parent_video"|"external"|"unavailable" }
export interface EvidenceItem extends SourceProvenance { signal_status?:string|null;semantic_status?:string|null; evidence_id:string;evidence_kind:"linked_signal"|"explicit_signal"|"explicit";signal_id:string|null;signal_type:string|null;evidence_type:string;statement:string;summary:string;evidence_text:string|null;claim_status:string|null;relationship_type:string|null;source_type:string;observed_at:string|null;strength:string|null;confidence:string|null;original_statement:string;original_evidence_text:string|null;statement_localized:boolean;evidence_localized:boolean;localization_stale:boolean }
export interface EvidencePage { items:EvidenceItem[];total:number;offset:number;limit:number;has_more:boolean }
export interface SignalFeedItem extends SourceProvenance { id:string;signal_type:string;statement:string;evidence_text:string|null;industry:string|null;customer_type:string|null;industry_taxonomy?:TaxonomyProjection|null;customer_taxonomy?:TaxonomyProjection|null;claim_status:string;confidence:string|null;evidence_strength:string|null;observed_at:string|null;source_type:string;video_title:string|null;channel_name?:string|null;opportunity_ids:string[];opportunities?:Array<{id:string;slug:string;name:string}>;original_statement?:string;original_evidence_text?:string|null;statement_localized?:boolean;evidence_localized?:boolean;localization_stale?:boolean }
export interface WatchlistOpportunity { id:string;slug:string;name:string;one_line_thesis:string|null;industry:string|null;market_stage:MarketStage }
export interface WatchlistItem { opportunity:WatchlistOpportunity;opportunity_score:string|null;confidence_score:string|null;hype_risk_score:string|null;momentum_score:string|null;added_at:string }
export interface WatchlistResult { items:WatchlistItem[] }
export interface WatchlistMembershipResult { opportunity_id:string;watchlisted:boolean;added_at:string|null }
export type ReviewType = "signal_validation"|"opportunity_match"|"opportunity_merge"|"opportunity_creation"|"opportunity_activation"|"hype_review"|"quality_review";
export type ReviewStatus = "pending"|"in_review"|"resolved"|"ignored";
export type ReviewDecisionName = "approve"|"merge"|"create_new"|"reject"|"ignore"|"defer";
export interface ReviewSignalContext { semantic_status?:string;actor_role?:string;evidence_role?:string;guardrail_reason_code?:string; id:string;signal_type:string;statement:string;evidence_text:string|null;claim_status:string;confidence:string;evidence_strength:string|null;industry:string|null;customer_type:string|null;problem:string|null;solution:string|null;observed_at:string|null;source_type:string }
export interface ReviewOpportunityContext { id:string;slug:string;name:string;one_line_thesis:string|null;industry:string|null;customer_type:string|null;problem:string|null;solution:string|null;market_stage:string;first_detected_at:string;last_activity_at:string }
export type ReadinessStatus = "pass"|"warning"|"fail";
export interface ReadinessCheck { status:ReadinessStatus;message:string;supporting_metrics:Record<string,unknown> }
export interface ActivationMetrics { active_signal_count:number;supporting_signal_count?:number;distinct_video_count:number;distinct_channel_count:number;latest_score:string|null;confidence_score:string|null;hype_risk:string|null;momentum_7d:string|null;first_detected_at:string;last_activity_at:string }
export interface ActivationReadiness { opportunity_id:string;checks:Record<string,ReadinessCheck>;overall:"ready"|"needs_review"|"not_ready";recommendation:"publish"|"defer"|"invalid_review";metrics:ActivationMetrics;duplicate_candidates:Array<{opportunity_id:string;name:string;status:string;overlap:number}> }
export interface ReviewContext { reason?:string;model_action?:string;proposed_opportunity_id?:string;signal?:ReviewSignalContext;candidates?:ReviewOpportunityContext[];source_opportunity?:ReviewOpportunityContext;canonical_opportunity?:ReviewOpportunityContext;readiness?:ActivationReadiness;recommendation?:string;metrics?:ActivationMetrics;duplicate_candidates?:ActivationReadiness["duplicate_candidates"] }
export interface ReviewTask { id:string;review_type:ReviewType;target_type:string;target_id:string;status:ReviewStatus;priority:number;assigned_to:string|null;resolved_by:string|null;decision:ReviewDecisionName|null;decision_notes:string|null;context:ReviewContext|null;created_at:string;updated_at:string;resolved_at:string|null }
export interface ReviewListResult { items:ReviewTask[];offset:number;limit:number }
export interface ReviewWorkflowResult { review_task_id:string;review_type:ReviewType;previous_status:ReviewStatus;status:ReviewStatus;decision:ReviewDecisionName|null;target_type:string;target_id:string;assigned_to:string|null;resolved_by:string|null;resolved_at:string|null;side_effects:Record<string,unknown> }
export type QueryValue = string | number | boolean | readonly (string | number | boolean)[] | undefined | null;
export type Query = Record<string, QueryValue>;
export interface ReviewDecision { decision:ReviewDecisionName;merge_target_opportunity_id?:string|null;decision_notes?:string|null }

export interface CandidateReview { id:string;status:string;assigned_to:string|null;created_at:string;decision:string|null;decision_notes:string|null }
export interface CandidateSummary { id:string;name:string;one_line_thesis:string|null;industry:string|null;customer_type:string|null;industry_taxonomy:TaxonomyProjection|null;customer_taxonomy:TaxonomyProjection|null;evidence_summary:EvidenceSummary;semantic_warning_count:number;readiness:ActivationReadiness;activation_review:CandidateReview|null;review_state:string;last_activity_at:string;score_at:string|null;trend_at:string|null;score_freshness:string;trend_freshness:string }
export interface CandidatePage { items:CandidateSummary[];total:number;offset:number;limit:number;has_more:boolean;counts:Record<string,number> }
export interface CandidateDetail { summary:CandidateSummary;opportunity:OpportunityDetailData & {status:string;updated_at:string};revisions:Array<{source_consolidation_id?:string|null;id:string;changed_by:string;changed_at:string;field:string;old_value:unknown;new_value:unknown;note:string|null}>;review_history:Array<{id:string;review_task_id:string;actor_id:string|null;event_type:string;previous_status:string|null;status:string;notes:string|null;created_at:string}>;legacy_reviews:Array<CandidateReview & {updated_at:string;resolved_at:string|null}>;translation_state:string;history_has_more:boolean }
