export type AppRole = "user" | "admin";
export interface CurrentUser { auth_user_id:string; user_profile_id:string; role:AppRole; email:string|null }
export type MarketStage = "unknown"|"emerging"|"accelerating"|"validated"|"crowded"|"mature"|"declining";
export interface TrendItem { window_type:string;period_start:string;period_end:string;aggregation_version:string;video_count:number;new_video_count:number;unique_channel_count:number;total_views:number;comment_count:number;pain_signal_count:number;demand_signal_count:number;purchase_intent_signal_count:number;revenue_signal_count:number;competitor_signal_count:number;momentum_score:string|null }
export interface EvidenceSummary { active_signal_count:number;distinct_video_count:number;distinct_channel_count:number;pain_signal_count:number;demand_signal_count:number;purchase_intent_signal_count:number;revenue_signal_count:number }
export interface TaxonomyProjection { code:string;label:string }
export interface RadarOpportunity { id:string;slug:string;name:string;one_line_thesis:string|null;industry:string|null;sub_industry:string|null;customer_type:string|null;industry_taxonomy?:TaxonomyProjection|null;customer_taxonomy?:TaxonomyProjection|null;business_model:string|null;market_stage:MarketStage;competition_level:string|null;build_difficulty:string|null;sales_difficulty:string|null;opportunity_score:string|null;confidence_score:string|null;hype_risk_score:string|null;trend:TrendItem|null;first_detected_at:string;last_activity_at:string;evidence_summary:EvidenceSummary;watchlisted:boolean }
export interface RadarResponse { items:RadarOpportunity[];total:number;offset:number;limit:number }
export interface OpportunityLibraryResponse { items:RadarOpportunity[];total:number;page:number;page_size:number;total_pages:number }
export interface ScoreItem { calculated_at:string;scoring_version:string;trend_velocity_score:string;demand_evidence_score:string;revenue_evidence_score:string;pain_severity_score:string;competition_white_space_score:string;build_feasibility_score:string;distribution_ease_score:string;opportunity_score:string;confidence_score:string|null;hype_risk_score:string|null }
export interface OpportunityDetailData { id:string;slug:string;name:string;one_line_thesis:string|null;industry:string|null;sub_industry:string|null;customer_type:string|null;industry_taxonomy?:TaxonomyProjection|null;customer_taxonomy?:TaxonomyProjection|null;problem:string|null;solution:string|null;business_model:string|null;primary_technology:string|null;typical_price_min:string|null;typical_price_max:string|null;typical_price_currency:string|null;typical_price_period:string|null;competition_level:string|null;build_difficulty:string|null;sales_difficulty:string|null;market_stage:MarketStage;first_detected_at:string;last_activity_at:string }
export interface OpportunityDetail { opportunity:OpportunityDetailData;current_intelligence:ScoreItem|null;trend_summary:Record<"7d"|"30d"|"90d",TrendItem|null>;evidence_summary:EvidenceSummary;watchlisted:boolean }
export interface EvidenceItem { evidence_id:string;evidence_type:string;summary:string;source_type:string;observed_at:string|null;strength:string|null;confidence:string|null;youtube_video_id:string|null;video_title:string|null }
export interface SignalFeedItem { id:string;signal_type:string;statement:string;evidence_text:string|null;industry:string|null;customer_type:string|null;industry_taxonomy?:TaxonomyProjection|null;customer_taxonomy?:TaxonomyProjection|null;claim_status:string;confidence:string|null;evidence_strength:string|null;observed_at:string|null;source_type:string;video_title:string|null;channel_name?:string|null;opportunity_ids:string[];opportunities?:Array<{id:string;slug:string;name:string}>;original_statement?:string;original_evidence_text?:string|null;statement_localized?:boolean;evidence_localized?:boolean;localization_stale?:boolean }
export interface WatchlistOpportunity { id:string;slug:string;name:string;one_line_thesis:string|null;industry:string|null;market_stage:MarketStage }
export interface WatchlistItem { opportunity:WatchlistOpportunity;opportunity_score:string|null;confidence_score:string|null;hype_risk_score:string|null;momentum_score:string|null;added_at:string }
export interface WatchlistResult { items:WatchlistItem[] }
export interface WatchlistMembershipResult { opportunity_id:string;watchlisted:boolean;added_at:string|null }
export type ReviewType = "signal_validation"|"opportunity_match"|"opportunity_merge"|"opportunity_creation"|"opportunity_activation"|"hype_review"|"quality_review";
export type ReviewStatus = "pending"|"in_review"|"resolved"|"ignored";
export type ReviewDecisionName = "approve"|"merge"|"create_new"|"reject"|"ignore"|"defer";
export interface ReviewSignalContext { id:string;signal_type:string;statement:string;evidence_text:string|null;claim_status:string;confidence:string;evidence_strength:string|null;industry:string|null;customer_type:string|null;problem:string|null;solution:string|null;observed_at:string|null;source_type:string }
export interface ReviewOpportunityContext { id:string;slug:string;name:string;one_line_thesis:string|null;industry:string|null;customer_type:string|null;problem:string|null;solution:string|null;market_stage:string;first_detected_at:string;last_activity_at:string }
export type ReadinessStatus = "pass"|"warning"|"fail";
export interface ReadinessCheck { status:ReadinessStatus;message:string;supporting_metrics:Record<string,unknown> }
export interface ActivationMetrics { active_signal_count:number;distinct_video_count:number;distinct_channel_count:number;latest_score:string|null;confidence_score:string|null;hype_risk:string|null;momentum_7d:string|null;first_detected_at:string;last_activity_at:string }
export interface ActivationReadiness { opportunity_id:string;checks:Record<string,ReadinessCheck>;overall:"ready"|"needs_review"|"not_ready";recommendation:"publish"|"defer"|"invalid_review";metrics:ActivationMetrics;duplicate_candidates:Array<{opportunity_id:string;name:string;status:string;overlap:number}> }
export interface ReviewContext { reason?:string;model_action?:string;proposed_opportunity_id?:string;signal?:ReviewSignalContext;candidates?:ReviewOpportunityContext[];source_opportunity?:ReviewOpportunityContext;canonical_opportunity?:ReviewOpportunityContext;readiness?:ActivationReadiness;recommendation?:string;metrics?:ActivationMetrics;duplicate_candidates?:ActivationReadiness["duplicate_candidates"] }
export interface ReviewTask { id:string;review_type:ReviewType;target_type:string;target_id:string;status:ReviewStatus;priority:number;assigned_to:string|null;resolved_by:string|null;decision:ReviewDecisionName|null;decision_notes:string|null;context:ReviewContext|null;created_at:string;updated_at:string;resolved_at:string|null }
export interface ReviewListResult { items:ReviewTask[];offset:number;limit:number }
export interface ReviewWorkflowResult { review_task_id:string;review_type:ReviewType;previous_status:ReviewStatus;status:ReviewStatus;decision:ReviewDecisionName|null;target_type:string;target_id:string;assigned_to:string|null;resolved_by:string|null;resolved_at:string|null;side_effects:Record<string,unknown> }
export type QueryValue = string | number | boolean | readonly (string | number | boolean)[] | undefined | null;
export type Query = Record<string, QueryValue>;
export interface ReviewDecision { decision:ReviewDecisionName;merge_target_opportunity_id?:string|null;decision_notes?:string|null }
