"use client";

import Link from "next/link";
import { useRouter,useSearchParams } from "next/navigation";
import { FormEvent,useCallback,useEffect,useMemo,useState } from "react";
import { ChevronLeft,ChevronRight,X } from "lucide-react";
import { ApiClient,ApiError } from "@/lib/api/client";
import { createClient } from "@/lib/auth/client";
import type { Query,SignalFeedItem } from "@/lib/api/types";
import { EmptyState,ErrorState } from "@/components/states/states";
import { PageHeader } from "@/components/ui/primitives";

const LIMIT=25;
const TYPES=["pain","demand","purchase_intent","revenue","pricing","customer","product_launch","growth","competition","distribution","workflow","technology","market_change","complaint","feature_request","adoption"];
const LABELS:Record<string,string>={pain:"Pain",demand:"Demand",purchase_intent:"Purchase intent",revenue:"Revenue",pricing:"Pricing",customer:"Customer",product_launch:"Product launch",growth:"Growth",competition:"Competition",distribution:"Distribution",workflow:"Workflow",technology:"Technology",market_change:"Market change",complaint:"Complaint",feature_request:"Feature request",adoption:"Adoption",fact:"Fact",creator_claim:"Creator claim",inferred:"Inferred",opinion:"Opinion",speculation:"Speculation",unknown:"Unknown"};
const FILTERS=["signal_type","industry","customer_type","opportunity_id","observed_after"] as const;
function date(value:string|null){return value?new Intl.DateTimeFormat("zh-CN",{year:"numeric",month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(value)):"—"}
function metric(value:string|null){if(value==null)return "—";const number=Number(value);return Number.isFinite(number)?number.toFixed(2):value}

export function SignalsFeed(){const router=useRouter();const search=useSearchParams();const serialized=search.toString();const params=useMemo(()=>new URLSearchParams(serialized),[serialized]);const offset=Math.max(0,Number(params.get("offset"))||0);const requestedLimit=Number(params.get("limit"));const limit=Number.isInteger(requestedLimit)&&requestedLimit>0&&requestedLimit<=100?requestedLimit:LIMIT;const [items,setItems]=useState<SignalFeedItem[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState<ApiError|null>(null);const [retry,setRetry]=useState(0);
  const navigate=useCallback((updates:Record<string,string|null>,reset=false)=>{const next=new URLSearchParams(serialized);Object.entries(updates).forEach(([key,value])=>value?next.set(key,value):next.delete(key));if(reset)next.delete("offset");const query=next.toString();router.replace(query?`/signals?${query}`:"/signals")},[router,serialized]);
  useEffect(()=>{let active=true;async function load(){setLoading(true);setError(null);try{const {data:{session}}=await createClient().auth.getSession();if(!session){router.replace("/login");return}const query:Query={offset,limit};FILTERS.forEach(key=>{const value=params.get(key);if(value)query[key]=value});const result=await new ApiClient(async()=>session.access_token).listSignals(query);if(active)setItems(Array.isArray(result)?result:[])}catch(reason){if(reason instanceof ApiError&&reason.status===401){router.replace("/login");return}if(active)setError(reason instanceof ApiError?reason:new ApiError(0,"无法加载商业信号"))}finally{if(active)setLoading(false)}}void load();return()=>{active=false}},[limit,offset,params,retry,router]);
  const filtered=FILTERS.some(key=>params.has(key));const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);navigate(Object.fromEntries(FILTERS.map(key=>[key,String(form.get(key)??"").trim()||null])),true)};const clear=()=>navigate(Object.fromEntries(FILTERS.map(key=>[key,null])),true);
  return <div className="space-y-5"><PageHeader title="Commercial Signals" description="A chronological feed of active, evidence-backed observations from the intelligence pipeline."/><form key={serialized} onSubmit={submit} className="grid gap-3 rounded-xl border bg-white p-4 md:grid-cols-2 xl:grid-cols-5 dark:bg-slate-950"><label><span className="mb-1 block text-xs text-slate-500">Signal Type</span><select name="signal_type" defaultValue={params.get("signal_type")??""} className="h-10 w-full rounded-md border bg-transparent px-3 text-sm"><option value="">All types</option>{TYPES.map(type=><option key={type} value={type}>{LABELS[type]}</option>)}</select></label><Text name="industry" label="Industry" value={params.get("industry")}/><Text name="customer_type" label="Customer Type" value={params.get("customer_type")}/><label><span className="mb-1 block text-xs text-slate-500">Observed After</span><input name="observed_after" type="date" defaultValue={params.get("observed_after")?.slice(0,10)??""} className="h-10 w-full rounded-md border bg-transparent px-3 text-sm"/></label><Text name="opportunity_id" label="Opportunity ID" value={params.get("opportunity_id")}/><div className="flex gap-2 xl:col-span-5"><button className="rounded-md bg-slate-950 px-4 py-2 text-sm text-white dark:bg-white dark:text-slate-950">应用筛选</button>{filtered&&<button type="button" onClick={clear} className="inline-flex items-center gap-1 rounded-md border px-4 py-2 text-sm"><X size={14}/>清除筛选</button>}</div></form>{loading?<FeedSkeleton/>:error?<ErrorState message={error.status===403?"你没有查看信号的权限":error.message} requestId={error.requestId??undefined} onRetry={()=>setRetry(value=>value+1)}/>:items.length?<ol className="divide-y rounded-xl border bg-white dark:bg-slate-950">{items.map(item=><SignalRow key={item.id} item={item}/>)}</ol>:<EmptyState title={filtered?"No signals match these filters.":"No active commercial signals are available yet."} description={filtered?"调整或清除筛选后重试。":"信号通过审核后会按观察时间显示。"} action={filtered?<button onClick={clear} className="mt-4 rounded-md border px-4 py-2 text-sm">清除筛选</button>:undefined}/>} {!loading&&!error&&items.length>0&&<nav aria-label="信号分页" className="flex justify-between border-t pt-4"><span className="text-sm text-slate-500">Offset {offset}</span><div className="flex gap-2"><button type="button" disabled={offset===0} onClick={()=>navigate({offset:String(Math.max(0,offset-limit))})} className="inline-flex items-center rounded-md border px-3 py-2 text-sm disabled:opacity-40"><ChevronLeft size={14}/>上一页</button><button type="button" disabled={items.length<limit} onClick={()=>navigate({offset:String(offset+limit)})} className="inline-flex items-center rounded-md border px-3 py-2 text-sm disabled:opacity-40">下一页<ChevronRight size={14}/></button></div></nav>}</div>}
function Text({name,label,value}:{name:string;label:string;value:string|null}){return <label><span className="mb-1 block text-xs text-slate-500">{label}</span><input name={name} defaultValue={value??""} className="h-10 w-full rounded-md border bg-transparent px-3 text-sm"/></label>}
function FeedSkeleton(){return <div aria-label="正在加载商业信号" className="space-y-px overflow-hidden rounded-xl border">{[1,2,3,4,5].map(item=><div key={item} className="h-36 animate-pulse bg-slate-100 dark:bg-slate-900"/>)}</div>}
function SignalRow({item}:{item:SignalFeedItem}){return <li><article className="grid gap-3 p-4 md:grid-cols-[9rem_minmax(0,1fr)_13rem]"><div><span className="rounded border px-2 py-1 text-xs font-semibold">{LABELS[item.signal_type]??item.signal_type}</span><time className="mt-3 block text-xs text-slate-500">{date(item.observed_at)}</time></div><div><h2 className="font-semibold leading-6">{item.statement}</h2>{item.evidence_text&&<blockquote className="mt-2 border-l-2 pl-3 text-sm leading-6 text-slate-600 dark:text-slate-300">{item.evidence_text}</blockquote>}<p className="mt-3 text-xs text-slate-500">{[item.industry,item.customer_type,LABELS[item.claim_status]??item.claim_status].filter(Boolean).join(" · ")}</p><div className="mt-2 flex flex-wrap gap-3 text-xs text-slate-500"><span>Source: {item.source_type}</span>{item.video_title&&<span>Video: {item.video_title}</span>}{item.opportunity_ids.map((id,index)=><Link key={id} href={`/opportunities/${id}`} className="font-medium hover:underline">Opportunity {index+1}</Link>)}</div></div><dl className="grid grid-cols-2 gap-2 self-start text-xs md:grid-cols-1"><Meta label="Confidence" value={metric(item.confidence)} hint="Evidence extraction confidence, not truth probability"/><Meta label="Evidence strength" value={metric(item.evidence_strength)}/></dl></article></li>}
function Meta({label,value,hint}:{label:string;value:string;hint?:string}){return <div title={hint} className="rounded-md bg-slate-50 p-2 dark:bg-slate-900"><dt className="text-slate-500">{label}</dt><dd className="mt-1 font-semibold tabular-nums">{value}</dd></div>}
